// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.xingyun.policy.api.model;

public interface BusTicketCheckItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.BusTicketCheckItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户ID.
   * </pre>
   *
   * <code>int64 cuid = 1;</code>
   */
  long getCuid();

  /**
   * <pre>
   * 企业ID.
   * </pre>
   *
   * <code>int64 eid = 2;</code>
   */
  long getEid();
}
