// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.xingyun.policy.api.model;

/**
 * <pre>
 * 汽车票规则详情.
 * </pre>
 *
 * Protobuf type {@code api.BusTicketRuleDetailItem}
 */
public  final class BusTicketRuleDetailItem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.BusTicketRuleDetailItem)
    BusTicketRuleDetailItemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BusTicketRuleDetailItem.newBuilder() to construct.
  private BusTicketRuleDetailItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BusTicketRuleDetailItem() {
    canUse_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BusTicketRuleDetailItem(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem.Builder subBuilder = null;
            if (settings_ != null) {
              subBuilder = settings_.toBuilder();
            }
            settings_ = input.readMessage(com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(settings_);
              settings_ = subBuilder.buildPartial();
            }

            break;
          }
          case 80: {

            canUse_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xingyun.policy.api.model.Model.internal_static_api_BusTicketRuleDetailItem_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xingyun.policy.api.model.Model.internal_static_api_BusTicketRuleDetailItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xingyun.policy.api.model.BusTicketRuleDetailItem.class, com.xingyun.policy.api.model.BusTicketRuleDetailItem.Builder.class);
  }

  public static final int SETTINGS_FIELD_NUMBER = 1;
  private com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem settings_;
  /**
   * <pre>
   * 汽车票规则基本信息.
   * </pre>
   *
   * <code>.api.BusTicketRuleItem.SettingItem settings = 1;</code>
   */
  public boolean hasSettings() {
    return settings_ != null;
  }
  /**
   * <pre>
   * 汽车票规则基本信息.
   * </pre>
   *
   * <code>.api.BusTicketRuleItem.SettingItem settings = 1;</code>
   */
  public com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem getSettings() {
    return settings_ == null ? com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem.getDefaultInstance() : settings_;
  }
  /**
   * <pre>
   * 汽车票规则基本信息.
   * </pre>
   *
   * <code>.api.BusTicketRuleItem.SettingItem settings = 1;</code>
   */
  public com.xingyun.policy.api.model.BusTicketRuleItem.SettingItemOrBuilder getSettingsOrBuilder() {
    return getSettings();
  }

  public static final int CAN_USE_FIELD_NUMBER = 10;
  private int canUse_;
  /**
   * <pre>
   * 是否可用 (0:不可用 1:可用有政策 2:可用无政策).
   * </pre>
   *
   * <code>int32 can_use = 10;</code>
   */
  public int getCanUse() {
    return canUse_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (settings_ != null) {
      output.writeMessage(1, getSettings());
    }
    if (canUse_ != 0) {
      output.writeInt32(10, canUse_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (settings_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSettings());
    }
    if (canUse_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, canUse_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xingyun.policy.api.model.BusTicketRuleDetailItem)) {
      return super.equals(obj);
    }
    com.xingyun.policy.api.model.BusTicketRuleDetailItem other = (com.xingyun.policy.api.model.BusTicketRuleDetailItem) obj;

    boolean result = true;
    result = result && (hasSettings() == other.hasSettings());
    if (hasSettings()) {
      result = result && getSettings()
          .equals(other.getSettings());
    }
    result = result && (getCanUse()
        == other.getCanUse());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSettings()) {
      hash = (37 * hash) + SETTINGS_FIELD_NUMBER;
      hash = (53 * hash) + getSettings().hashCode();
    }
    hash = (37 * hash) + CAN_USE_FIELD_NUMBER;
    hash = (53 * hash) + getCanUse();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xingyun.policy.api.model.BusTicketRuleDetailItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.model.BusTicketRuleDetailItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.BusTicketRuleDetailItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.model.BusTicketRuleDetailItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.BusTicketRuleDetailItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.model.BusTicketRuleDetailItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.BusTicketRuleDetailItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.model.BusTicketRuleDetailItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.BusTicketRuleDetailItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.model.BusTicketRuleDetailItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.BusTicketRuleDetailItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.model.BusTicketRuleDetailItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xingyun.policy.api.model.BusTicketRuleDetailItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 汽车票规则详情.
   * </pre>
   *
   * Protobuf type {@code api.BusTicketRuleDetailItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.BusTicketRuleDetailItem)
      com.xingyun.policy.api.model.BusTicketRuleDetailItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xingyun.policy.api.model.Model.internal_static_api_BusTicketRuleDetailItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xingyun.policy.api.model.Model.internal_static_api_BusTicketRuleDetailItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xingyun.policy.api.model.BusTicketRuleDetailItem.class, com.xingyun.policy.api.model.BusTicketRuleDetailItem.Builder.class);
    }

    // Construct using com.xingyun.policy.api.model.BusTicketRuleDetailItem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (settingsBuilder_ == null) {
        settings_ = null;
      } else {
        settings_ = null;
        settingsBuilder_ = null;
      }
      canUse_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xingyun.policy.api.model.Model.internal_static_api_BusTicketRuleDetailItem_descriptor;
    }

    public com.xingyun.policy.api.model.BusTicketRuleDetailItem getDefaultInstanceForType() {
      return com.xingyun.policy.api.model.BusTicketRuleDetailItem.getDefaultInstance();
    }

    public com.xingyun.policy.api.model.BusTicketRuleDetailItem build() {
      com.xingyun.policy.api.model.BusTicketRuleDetailItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.xingyun.policy.api.model.BusTicketRuleDetailItem buildPartial() {
      com.xingyun.policy.api.model.BusTicketRuleDetailItem result = new com.xingyun.policy.api.model.BusTicketRuleDetailItem(this);
      if (settingsBuilder_ == null) {
        result.settings_ = settings_;
      } else {
        result.settings_ = settingsBuilder_.build();
      }
      result.canUse_ = canUse_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xingyun.policy.api.model.BusTicketRuleDetailItem) {
        return mergeFrom((com.xingyun.policy.api.model.BusTicketRuleDetailItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xingyun.policy.api.model.BusTicketRuleDetailItem other) {
      if (other == com.xingyun.policy.api.model.BusTicketRuleDetailItem.getDefaultInstance()) return this;
      if (other.hasSettings()) {
        mergeSettings(other.getSettings());
      }
      if (other.getCanUse() != 0) {
        setCanUse(other.getCanUse());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xingyun.policy.api.model.BusTicketRuleDetailItem parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xingyun.policy.api.model.BusTicketRuleDetailItem) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem settings_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem, com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem.Builder, com.xingyun.policy.api.model.BusTicketRuleItem.SettingItemOrBuilder> settingsBuilder_;
    /**
     * <pre>
     * 汽车票规则基本信息.
     * </pre>
     *
     * <code>.api.BusTicketRuleItem.SettingItem settings = 1;</code>
     */
    public boolean hasSettings() {
      return settingsBuilder_ != null || settings_ != null;
    }
    /**
     * <pre>
     * 汽车票规则基本信息.
     * </pre>
     *
     * <code>.api.BusTicketRuleItem.SettingItem settings = 1;</code>
     */
    public com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem getSettings() {
      if (settingsBuilder_ == null) {
        return settings_ == null ? com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem.getDefaultInstance() : settings_;
      } else {
        return settingsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 汽车票规则基本信息.
     * </pre>
     *
     * <code>.api.BusTicketRuleItem.SettingItem settings = 1;</code>
     */
    public Builder setSettings(com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem value) {
      if (settingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        settings_ = value;
        onChanged();
      } else {
        settingsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 汽车票规则基本信息.
     * </pre>
     *
     * <code>.api.BusTicketRuleItem.SettingItem settings = 1;</code>
     */
    public Builder setSettings(
        com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem.Builder builderForValue) {
      if (settingsBuilder_ == null) {
        settings_ = builderForValue.build();
        onChanged();
      } else {
        settingsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 汽车票规则基本信息.
     * </pre>
     *
     * <code>.api.BusTicketRuleItem.SettingItem settings = 1;</code>
     */
    public Builder mergeSettings(com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem value) {
      if (settingsBuilder_ == null) {
        if (settings_ != null) {
          settings_ =
            com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem.newBuilder(settings_).mergeFrom(value).buildPartial();
        } else {
          settings_ = value;
        }
        onChanged();
      } else {
        settingsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 汽车票规则基本信息.
     * </pre>
     *
     * <code>.api.BusTicketRuleItem.SettingItem settings = 1;</code>
     */
    public Builder clearSettings() {
      if (settingsBuilder_ == null) {
        settings_ = null;
        onChanged();
      } else {
        settings_ = null;
        settingsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 汽车票规则基本信息.
     * </pre>
     *
     * <code>.api.BusTicketRuleItem.SettingItem settings = 1;</code>
     */
    public com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem.Builder getSettingsBuilder() {
      
      onChanged();
      return getSettingsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 汽车票规则基本信息.
     * </pre>
     *
     * <code>.api.BusTicketRuleItem.SettingItem settings = 1;</code>
     */
    public com.xingyun.policy.api.model.BusTicketRuleItem.SettingItemOrBuilder getSettingsOrBuilder() {
      if (settingsBuilder_ != null) {
        return settingsBuilder_.getMessageOrBuilder();
      } else {
        return settings_ == null ?
            com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem.getDefaultInstance() : settings_;
      }
    }
    /**
     * <pre>
     * 汽车票规则基本信息.
     * </pre>
     *
     * <code>.api.BusTicketRuleItem.SettingItem settings = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem, com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem.Builder, com.xingyun.policy.api.model.BusTicketRuleItem.SettingItemOrBuilder> 
        getSettingsFieldBuilder() {
      if (settingsBuilder_ == null) {
        settingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem, com.xingyun.policy.api.model.BusTicketRuleItem.SettingItem.Builder, com.xingyun.policy.api.model.BusTicketRuleItem.SettingItemOrBuilder>(
                getSettings(),
                getParentForChildren(),
                isClean());
        settings_ = null;
      }
      return settingsBuilder_;
    }

    private int canUse_ ;
    /**
     * <pre>
     * 是否可用 (0:不可用 1:可用有政策 2:可用无政策).
     * </pre>
     *
     * <code>int32 can_use = 10;</code>
     */
    public int getCanUse() {
      return canUse_;
    }
    /**
     * <pre>
     * 是否可用 (0:不可用 1:可用有政策 2:可用无政策).
     * </pre>
     *
     * <code>int32 can_use = 10;</code>
     */
    public Builder setCanUse(int value) {
      
      canUse_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否可用 (0:不可用 1:可用有政策 2:可用无政策).
     * </pre>
     *
     * <code>int32 can_use = 10;</code>
     */
    public Builder clearCanUse() {
      
      canUse_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.BusTicketRuleDetailItem)
  }

  // @@protoc_insertion_point(class_scope:api.BusTicketRuleDetailItem)
  private static final com.xingyun.policy.api.model.BusTicketRuleDetailItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xingyun.policy.api.model.BusTicketRuleDetailItem();
  }

  public static com.xingyun.policy.api.model.BusTicketRuleDetailItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BusTicketRuleDetailItem>
      PARSER = new com.google.protobuf.AbstractParser<BusTicketRuleDetailItem>() {
    public BusTicketRuleDetailItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BusTicketRuleDetailItem(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BusTicketRuleDetailItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BusTicketRuleDetailItem> getParserForType() {
    return PARSER;
  }

  public com.xingyun.policy.api.model.BusTicketRuleDetailItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

