// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.xingyun.policy.api.model;

public interface DepartmentItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.DepartmentItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 企业编号.
   * </pre>
   *
   * <code>int64 eid = 1;</code>
   */
  long getEid();

  /**
   * <pre>
   * 部门编号.
   * </pre>
   *
   * <code>int64 department_id = 2;</code>
   */
  long getDepartmentId();

  /**
   * <pre>
   * 部门名称.
   * </pre>
   *
   * <code>string department_name = 3;</code>
   */
  java.lang.String getDepartmentName();
  /**
   * <pre>
   * 部门名称.
   * </pre>
   *
   * <code>string department_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getDepartmentNameBytes();

  /**
   * <pre>
   *总员工数.
   * </pre>
   *
   * <code>int32 total_number = 4;</code>
   */
  int getTotalNumber();
}
