// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.xingyun.policy.api.model;

public interface FlightRuleDetailItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.FlightRuleDetailItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 规则基本信息.
   * </pre>
   *
   * <code>.api.FlightRuleItem.SettingItem settings = 1;</code>
   */
  boolean hasSettings();
  /**
   * <pre>
   * 规则基本信息.
   * </pre>
   *
   * <code>.api.FlightRuleItem.SettingItem settings = 1;</code>
   */
  com.xingyun.policy.api.model.FlightRuleItem.SettingItem getSettings();
  /**
   * <pre>
   * 规则基本信息.
   * </pre>
   *
   * <code>.api.FlightRuleItem.SettingItem settings = 1;</code>
   */
  com.xingyun.policy.api.model.FlightRuleItem.SettingItemOrBuilder getSettingsOrBuilder();

  /**
   * <pre>
   * 是否可用 (0:不可用 1:可用有政策 2:可用无政策).
   * </pre>
   *
   * <code>int32 can_use = 21;</code>
   */
  int getCanUse();

  /**
   * <pre>
   * 用户ID.
   * </pre>
   *
   * <code>int64 cuid = 22;</code>
   */
  long getCuid();

  /**
   * <pre>
   * 时间限制信息.
   * </pre>
   *
   * <code>repeated .api.TimeItem times = 23;</code>
   */
  java.util.List<com.xingyun.policy.api.model.TimeItem> 
      getTimesList();
  /**
   * <pre>
   * 时间限制信息.
   * </pre>
   *
   * <code>repeated .api.TimeItem times = 23;</code>
   */
  com.xingyun.policy.api.model.TimeItem getTimes(int index);
  /**
   * <pre>
   * 时间限制信息.
   * </pre>
   *
   * <code>repeated .api.TimeItem times = 23;</code>
   */
  int getTimesCount();
  /**
   * <pre>
   * 时间限制信息.
   * </pre>
   *
   * <code>repeated .api.TimeItem times = 23;</code>
   */
  java.util.List<? extends com.xingyun.policy.api.model.TimeItemOrBuilder> 
      getTimesOrBuilderList();
  /**
   * <pre>
   * 时间限制信息.
   * </pre>
   *
   * <code>repeated .api.TimeItem times = 23;</code>
   */
  com.xingyun.policy.api.model.TimeItemOrBuilder getTimesOrBuilder(
      int index);
}
