// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.xingyun.policy.api.model;

public interface FlightCheckItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.FlightCheckItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户ID.
   * </pre>
   *
   * <code>int64 cuid = 1;</code>
   */
  long getCuid();

  /**
   * <pre>
   * 企业ID.
   * </pre>
   *
   * <code>int64 eid = 2;</code>
   */
  long getEid();

  /**
   * <pre>
   * 是否强制下单.
   * </pre>
   *
   * <code>bool force = 3;</code>
   */
  boolean getForce();

  /**
   * <pre>
   * 舱位类型 Y:经济 C: 公务舱 F: 头等舱
   * </pre>
   *
   * <code>string carbin_type = 4;</code>
   */
  java.lang.String getCarbinType();
  /**
   * <pre>
   * 舱位类型 Y:经济 C: 公务舱 F: 头等舱
   * </pre>
   *
   * <code>string carbin_type = 4;</code>
   */
  com.google.protobuf.ByteString
      getCarbinTypeBytes();

  /**
   * <pre>
   * 出发时间,unix 秒.
   * </pre>
   *
   * <code>int32 depart_time = 5;</code>
   */
  int getDepartTime();

  /**
   * <pre>
   * 到达时间.
   * </pre>
   *
   * <code>int32 arrive_time = 6;</code>
   */
  int getArriveTime();

  /**
   * <pre>
   * 舱位折扣:万分之n.
   * </pre>
   *
   * <code>int32 discount = 7;</code>
   */
  int getDiscount();

  /**
   * <pre>
   * 航空意外险：分.
   * </pre>
   *
   * <code>int64 insurance = 8;</code>
   */
  long getInsurance();

  /**
   * <pre>
   * 出发经度.
   * </pre>
   *
   * <code>double depart_longitude = 9;</code>
   */
  double getDepartLongitude();

  /**
   * <pre>
   * 出发纬度.
   * </pre>
   *
   * <code>double depart_latitude = 10;</code>
   */
  double getDepartLatitude();

  /**
   * <pre>
   * 到达经度.
   * </pre>
   *
   * <code>double arrive_longitude = 11;</code>
   */
  double getArriveLongitude();

  /**
   * <pre>
   * 到达纬度.
   * </pre>
   *
   * <code>double arrive_latitude = 12;</code>
   */
  double getArriveLatitude();

  /**
   * <pre>
   * 审批城市列表.
   * </pre>
   *
   * <code>repeated .api.FlightCheckItem.CityItem approve_cities = 13;</code>
   */
  java.util.List<com.xingyun.policy.api.model.FlightCheckItem.CityItem> 
      getApproveCitiesList();
  /**
   * <pre>
   * 审批城市列表.
   * </pre>
   *
   * <code>repeated .api.FlightCheckItem.CityItem approve_cities = 13;</code>
   */
  com.xingyun.policy.api.model.FlightCheckItem.CityItem getApproveCities(int index);
  /**
   * <pre>
   * 审批城市列表.
   * </pre>
   *
   * <code>repeated .api.FlightCheckItem.CityItem approve_cities = 13;</code>
   */
  int getApproveCitiesCount();
  /**
   * <pre>
   * 审批城市列表.
   * </pre>
   *
   * <code>repeated .api.FlightCheckItem.CityItem approve_cities = 13;</code>
   */
  java.util.List<? extends com.xingyun.policy.api.model.FlightCheckItem.CityItemOrBuilder> 
      getApproveCitiesOrBuilderList();
  /**
   * <pre>
   * 审批城市列表.
   * </pre>
   *
   * <code>repeated .api.FlightCheckItem.CityItem approve_cities = 13;</code>
   */
  com.xingyun.policy.api.model.FlightCheckItem.CityItemOrBuilder getApproveCitiesOrBuilder(
      int index);

  /**
   * <pre>
   * 出发城市代码.
   * </pre>
   *
   * <code>string depart_city_code = 14;</code>
   */
  java.lang.String getDepartCityCode();
  /**
   * <pre>
   * 出发城市代码.
   * </pre>
   *
   * <code>string depart_city_code = 14;</code>
   */
  com.google.protobuf.ByteString
      getDepartCityCodeBytes();

  /**
   * <pre>
   * 到达城市代码.
   * </pre>
   *
   * <code>string arrive_city_code = 15;</code>
   */
  java.lang.String getArriveCityCode();
  /**
   * <pre>
   * 到达城市代码.
   * </pre>
   *
   * <code>string arrive_city_code = 15;</code>
   */
  com.google.protobuf.ByteString
      getArriveCityCodeBytes();

  /**
   * <pre>
   * 航空公司.
   * </pre>
   *
   * <code>string carrier_code = 16;</code>
   */
  java.lang.String getCarrierCode();
  /**
   * <pre>
   * 航空公司.
   * </pre>
   *
   * <code>string carrier_code = 16;</code>
   */
  com.google.protobuf.ByteString
      getCarrierCodeBytes();

  /**
   * <pre>
   * 出发城市名.
   * </pre>
   *
   * <code>string depart_city_name = 17;</code>
   */
  java.lang.String getDepartCityName();
  /**
   * <pre>
   * 出发城市名.
   * </pre>
   *
   * <code>string depart_city_name = 17;</code>
   */
  com.google.protobuf.ByteString
      getDepartCityNameBytes();

  /**
   * <pre>
   * 到达城市名.
   * </pre>
   *
   * <code>string arrive_city_name = 18;</code>
   */
  java.lang.String getArriveCityName();
  /**
   * <pre>
   * 到达城市名.
   * </pre>
   *
   * <code>string arrive_city_name = 18;</code>
   */
  com.google.protobuf.ByteString
      getArriveCityNameBytes();
}
