// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.xingyun.policy.api.model;

public interface FlightRuleItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.FlightRuleItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 飞机规则信息.
   * </pre>
   *
   * <code>.api.FlightRuleItem.SettingItem settings = 1;</code>
   */
  boolean hasSettings();
  /**
   * <pre>
   * 飞机规则信息.
   * </pre>
   *
   * <code>.api.FlightRuleItem.SettingItem settings = 1;</code>
   */
  com.xingyun.policy.api.model.FlightRuleItem.SettingItem getSettings();
  /**
   * <pre>
   * 飞机规则信息.
   * </pre>
   *
   * <code>.api.FlightRuleItem.SettingItem settings = 1;</code>
   */
  com.xingyun.policy.api.model.FlightRuleItem.SettingItemOrBuilder getSettingsOrBuilder();

  /**
   * <pre>
   * 时间限制.
   * </pre>
   *
   * <code>repeated .api.TimeItem time_settings = 2;</code>
   */
  java.util.List<com.xingyun.policy.api.model.TimeItem> 
      getTimeSettingsList();
  /**
   * <pre>
   * 时间限制.
   * </pre>
   *
   * <code>repeated .api.TimeItem time_settings = 2;</code>
   */
  com.xingyun.policy.api.model.TimeItem getTimeSettings(int index);
  /**
   * <pre>
   * 时间限制.
   * </pre>
   *
   * <code>repeated .api.TimeItem time_settings = 2;</code>
   */
  int getTimeSettingsCount();
  /**
   * <pre>
   * 时间限制.
   * </pre>
   *
   * <code>repeated .api.TimeItem time_settings = 2;</code>
   */
  java.util.List<? extends com.xingyun.policy.api.model.TimeItemOrBuilder> 
      getTimeSettingsOrBuilderList();
  /**
   * <pre>
   * 时间限制.
   * </pre>
   *
   * <code>repeated .api.TimeItem time_settings = 2;</code>
   */
  com.xingyun.policy.api.model.TimeItemOrBuilder getTimeSettingsOrBuilder(
      int index);

  /**
   * <pre>
   * 部门列表信息
   * </pre>
   *
   * <code>repeated .api.DepartmentItem departments = 3;</code>
   */
  java.util.List<com.xingyun.policy.api.model.DepartmentItem> 
      getDepartmentsList();
  /**
   * <pre>
   * 部门列表信息
   * </pre>
   *
   * <code>repeated .api.DepartmentItem departments = 3;</code>
   */
  com.xingyun.policy.api.model.DepartmentItem getDepartments(int index);
  /**
   * <pre>
   * 部门列表信息
   * </pre>
   *
   * <code>repeated .api.DepartmentItem departments = 3;</code>
   */
  int getDepartmentsCount();
  /**
   * <pre>
   * 部门列表信息
   * </pre>
   *
   * <code>repeated .api.DepartmentItem departments = 3;</code>
   */
  java.util.List<? extends com.xingyun.policy.api.model.DepartmentItemOrBuilder> 
      getDepartmentsOrBuilderList();
  /**
   * <pre>
   * 部门列表信息
   * </pre>
   *
   * <code>repeated .api.DepartmentItem departments = 3;</code>
   */
  com.xingyun.policy.api.model.DepartmentItemOrBuilder getDepartmentsOrBuilder(
      int index);

  /**
   * <pre>
   * 角色列表.
   * </pre>
   *
   * <code>repeated .api.RoleItem roles = 4;</code>
   */
  java.util.List<com.xingyun.policy.api.model.RoleItem> 
      getRolesList();
  /**
   * <pre>
   * 角色列表.
   * </pre>
   *
   * <code>repeated .api.RoleItem roles = 4;</code>
   */
  com.xingyun.policy.api.model.RoleItem getRoles(int index);
  /**
   * <pre>
   * 角色列表.
   * </pre>
   *
   * <code>repeated .api.RoleItem roles = 4;</code>
   */
  int getRolesCount();
  /**
   * <pre>
   * 角色列表.
   * </pre>
   *
   * <code>repeated .api.RoleItem roles = 4;</code>
   */
  java.util.List<? extends com.xingyun.policy.api.model.RoleItemOrBuilder> 
      getRolesOrBuilderList();
  /**
   * <pre>
   * 角色列表.
   * </pre>
   *
   * <code>repeated .api.RoleItem roles = 4;</code>
   */
  com.xingyun.policy.api.model.RoleItemOrBuilder getRolesOrBuilder(
      int index);
}
