// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.xingyun.policy.api.model;

public interface HotelCheckItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.HotelCheckItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户ID.
   * </pre>
   *
   * <code>int64 cuid = 1;</code>
   */
  long getCuid();

  /**
   * <pre>
   * 企业ID.
   * </pre>
   *
   * <code>int64 eid = 2;</code>
   */
  long getEid();

  /**
   * <pre>
   * 星级（1：经济型 2：二星 3：三星 4：四星 5: 五星）.
   * </pre>
   *
   * <code>string star_level = 3;</code>
   */
  java.lang.String getStarLevel();
  /**
   * <pre>
   * 星级（1：经济型 2：二星 3：三星 4：四星 5: 五星）.
   * </pre>
   *
   * <code>string star_level = 3;</code>
   */
  com.google.protobuf.ByteString
      getStarLevelBytes();

  /**
   * <pre>
   * 预订：unix秒.
   * </pre>
   *
   * <code>int32 booking_time = 4;</code>
   */
  int getBookingTime();

  /**
   * <pre>
   * 城市码.
   * </pre>
   *
   * <code>string city = 5;</code>
   */
  java.lang.String getCity();
  /**
   * <pre>
   * 城市码.
   * </pre>
   *
   * <code>string city = 5;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <pre>
   * 价格，分.
   * </pre>
   *
   * <code>int64 price = 6;</code>
   */
  long getPrice();

  /**
   * <pre>
   * 审批单城市
   * </pre>
   *
   * <code>repeated string approve_cities = 7;</code>
   */
  java.util.List<java.lang.String>
      getApproveCitiesList();
  /**
   * <pre>
   * 审批单城市
   * </pre>
   *
   * <code>repeated string approve_cities = 7;</code>
   */
  int getApproveCitiesCount();
  /**
   * <pre>
   * 审批单城市
   * </pre>
   *
   * <code>repeated string approve_cities = 7;</code>
   */
  java.lang.String getApproveCities(int index);
  /**
   * <pre>
   * 审批单城市
   * </pre>
   *
   * <code>repeated string approve_cities = 7;</code>
   */
  com.google.protobuf.ByteString
      getApproveCitiesBytes(int index);
}
