// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.xingyun.policy.api.model;

public interface LocationItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.LocationItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * foreignUUID.
   * </pre>
   *
   * <code>string uuid = 1;</code>
   */
  java.lang.String getUuid();
  /**
   * <pre>
   * foreignUUID.
   * </pre>
   *
   * <code>string uuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <pre>
   * 位置UUID.
   * </pre>
   *
   * <code>string location_uuid = 2;</code>
   */
  java.lang.String getLocationUuid();
  /**
   * <pre>
   * 位置UUID.
   * </pre>
   *
   * <code>string location_uuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getLocationUuidBytes();

  /**
   * <pre>
   * 省id.
   * </pre>
   *
   * <code>int32 province_id = 3;</code>
   */
  int getProvinceId();

  /**
   * <pre>
   * 省名.
   * </pre>
   *
   * <code>string provinc_name = 4;</code>
   */
  java.lang.String getProvincName();
  /**
   * <pre>
   * 省名.
   * </pre>
   *
   * <code>string provinc_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getProvincNameBytes();

  /**
   * <pre>
   * 城市id.
   * </pre>
   *
   * <code>int32 city_id = 5;</code>
   */
  int getCityId();

  /**
   * <pre>
   * 城市名.
   * </pre>
   *
   * <code>string city_name = 6;</code>
   */
  java.lang.String getCityName();
  /**
   * <pre>
   * 城市名.
   * </pre>
   *
   * <code>string city_name = 6;</code>
   */
  com.google.protobuf.ByteString
      getCityNameBytes();

  /**
   * <pre>
   * 县id.
   * </pre>
   *
   * <code>int32 county_id = 7;</code>
   */
  int getCountyId();

  /**
   * <pre>
   * 县名.
   * </pre>
   *
   * <code>string county_name = 8;</code>
   */
  java.lang.String getCountyName();
  /**
   * <pre>
   * 县名.
   * </pre>
   *
   * <code>string county_name = 8;</code>
   */
  com.google.protobuf.ByteString
      getCountyNameBytes();

  /**
   * <pre>
   * 地址.
   * </pre>
   *
   * <code>string address = 9;</code>
   */
  java.lang.String getAddress();
  /**
   * <pre>
   * 地址.
   * </pre>
   *
   * <code>string address = 9;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <pre>
   * 半径.
   * </pre>
   *
   * <code>double radis = 10;</code>
   */
  double getRadis();

  /**
   * <pre>
   * 经度.
   * </pre>
   *
   * <code>double longitude = 11;</code>
   */
  double getLongitude();

  /**
   * <pre>
   * 纬度.
   * </pre>
   *
   * <code>double latitude = 12;</code>
   */
  double getLatitude();

  /**
   * <code>.api.LocationSrcType location_src = 13;</code>
   */
  int getLocationSrcValue();
  /**
   * <code>.api.LocationSrcType location_src = 13;</code>
   */
  com.xingyun.policy.api.enums.LocationSrcType getLocationSrc();
}
