// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.xingyun.policy.api.model;

/**
 * <pre>
 * 支付规则详情.
 * </pre>
 *
 * Protobuf type {@code api.PayRuleDetailItem}
 */
public  final class PayRuleDetailItem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.PayRuleDetailItem)
    PayRuleDetailItemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PayRuleDetailItem.newBuilder() to construct.
  private PayRuleDetailItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PayRuleDetailItem() {
    payTypes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PayRuleDetailItem(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.xingyun.policy.api.model.PayRuleItem.SettingItem.Builder subBuilder = null;
            if (settings_ != null) {
              subBuilder = settings_.toBuilder();
            }
            settings_ = input.readMessage(com.xingyun.policy.api.model.PayRuleItem.SettingItem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(settings_);
              settings_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              payTypes_ = new java.util.ArrayList<com.xingyun.policy.api.model.PayRuleItem.PayTypeItem>();
              mutable_bitField0_ |= 0x00000002;
            }
            payTypes_.add(
                input.readMessage(com.xingyun.policy.api.model.PayRuleItem.PayTypeItem.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        payTypes_ = java.util.Collections.unmodifiableList(payTypes_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xingyun.policy.api.model.Model.internal_static_api_PayRuleDetailItem_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xingyun.policy.api.model.Model.internal_static_api_PayRuleDetailItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xingyun.policy.api.model.PayRuleDetailItem.class, com.xingyun.policy.api.model.PayRuleDetailItem.Builder.class);
  }

  private int bitField0_;
  public static final int SETTINGS_FIELD_NUMBER = 1;
  private com.xingyun.policy.api.model.PayRuleItem.SettingItem settings_;
  /**
   * <pre>
   * 支付规则基本信息.
   * </pre>
   *
   * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
   */
  public boolean hasSettings() {
    return settings_ != null;
  }
  /**
   * <pre>
   * 支付规则基本信息.
   * </pre>
   *
   * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
   */
  public com.xingyun.policy.api.model.PayRuleItem.SettingItem getSettings() {
    return settings_ == null ? com.xingyun.policy.api.model.PayRuleItem.SettingItem.getDefaultInstance() : settings_;
  }
  /**
   * <pre>
   * 支付规则基本信息.
   * </pre>
   *
   * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
   */
  public com.xingyun.policy.api.model.PayRuleItem.SettingItemOrBuilder getSettingsOrBuilder() {
    return getSettings();
  }

  public static final int PAY_TYPES_FIELD_NUMBER = 2;
  private java.util.List<com.xingyun.policy.api.model.PayRuleItem.PayTypeItem> payTypes_;
  /**
   * <pre>
   * 业务支付方式列表.
   * </pre>
   *
   * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
   */
  public java.util.List<com.xingyun.policy.api.model.PayRuleItem.PayTypeItem> getPayTypesList() {
    return payTypes_;
  }
  /**
   * <pre>
   * 业务支付方式列表.
   * </pre>
   *
   * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
   */
  public java.util.List<? extends com.xingyun.policy.api.model.PayRuleItem.PayTypeItemOrBuilder> 
      getPayTypesOrBuilderList() {
    return payTypes_;
  }
  /**
   * <pre>
   * 业务支付方式列表.
   * </pre>
   *
   * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
   */
  public int getPayTypesCount() {
    return payTypes_.size();
  }
  /**
   * <pre>
   * 业务支付方式列表.
   * </pre>
   *
   * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
   */
  public com.xingyun.policy.api.model.PayRuleItem.PayTypeItem getPayTypes(int index) {
    return payTypes_.get(index);
  }
  /**
   * <pre>
   * 业务支付方式列表.
   * </pre>
   *
   * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
   */
  public com.xingyun.policy.api.model.PayRuleItem.PayTypeItemOrBuilder getPayTypesOrBuilder(
      int index) {
    return payTypes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (settings_ != null) {
      output.writeMessage(1, getSettings());
    }
    for (int i = 0; i < payTypes_.size(); i++) {
      output.writeMessage(2, payTypes_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (settings_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSettings());
    }
    for (int i = 0; i < payTypes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, payTypes_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xingyun.policy.api.model.PayRuleDetailItem)) {
      return super.equals(obj);
    }
    com.xingyun.policy.api.model.PayRuleDetailItem other = (com.xingyun.policy.api.model.PayRuleDetailItem) obj;

    boolean result = true;
    result = result && (hasSettings() == other.hasSettings());
    if (hasSettings()) {
      result = result && getSettings()
          .equals(other.getSettings());
    }
    result = result && getPayTypesList()
        .equals(other.getPayTypesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSettings()) {
      hash = (37 * hash) + SETTINGS_FIELD_NUMBER;
      hash = (53 * hash) + getSettings().hashCode();
    }
    if (getPayTypesCount() > 0) {
      hash = (37 * hash) + PAY_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getPayTypesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xingyun.policy.api.model.PayRuleDetailItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.model.PayRuleDetailItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.PayRuleDetailItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.model.PayRuleDetailItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.PayRuleDetailItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.model.PayRuleDetailItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.PayRuleDetailItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.model.PayRuleDetailItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.PayRuleDetailItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.model.PayRuleDetailItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.PayRuleDetailItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.model.PayRuleDetailItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xingyun.policy.api.model.PayRuleDetailItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 支付规则详情.
   * </pre>
   *
   * Protobuf type {@code api.PayRuleDetailItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.PayRuleDetailItem)
      com.xingyun.policy.api.model.PayRuleDetailItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xingyun.policy.api.model.Model.internal_static_api_PayRuleDetailItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xingyun.policy.api.model.Model.internal_static_api_PayRuleDetailItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xingyun.policy.api.model.PayRuleDetailItem.class, com.xingyun.policy.api.model.PayRuleDetailItem.Builder.class);
    }

    // Construct using com.xingyun.policy.api.model.PayRuleDetailItem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPayTypesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (settingsBuilder_ == null) {
        settings_ = null;
      } else {
        settings_ = null;
        settingsBuilder_ = null;
      }
      if (payTypesBuilder_ == null) {
        payTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        payTypesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xingyun.policy.api.model.Model.internal_static_api_PayRuleDetailItem_descriptor;
    }

    public com.xingyun.policy.api.model.PayRuleDetailItem getDefaultInstanceForType() {
      return com.xingyun.policy.api.model.PayRuleDetailItem.getDefaultInstance();
    }

    public com.xingyun.policy.api.model.PayRuleDetailItem build() {
      com.xingyun.policy.api.model.PayRuleDetailItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.xingyun.policy.api.model.PayRuleDetailItem buildPartial() {
      com.xingyun.policy.api.model.PayRuleDetailItem result = new com.xingyun.policy.api.model.PayRuleDetailItem(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (settingsBuilder_ == null) {
        result.settings_ = settings_;
      } else {
        result.settings_ = settingsBuilder_.build();
      }
      if (payTypesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          payTypes_ = java.util.Collections.unmodifiableList(payTypes_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.payTypes_ = payTypes_;
      } else {
        result.payTypes_ = payTypesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xingyun.policy.api.model.PayRuleDetailItem) {
        return mergeFrom((com.xingyun.policy.api.model.PayRuleDetailItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xingyun.policy.api.model.PayRuleDetailItem other) {
      if (other == com.xingyun.policy.api.model.PayRuleDetailItem.getDefaultInstance()) return this;
      if (other.hasSettings()) {
        mergeSettings(other.getSettings());
      }
      if (payTypesBuilder_ == null) {
        if (!other.payTypes_.isEmpty()) {
          if (payTypes_.isEmpty()) {
            payTypes_ = other.payTypes_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePayTypesIsMutable();
            payTypes_.addAll(other.payTypes_);
          }
          onChanged();
        }
      } else {
        if (!other.payTypes_.isEmpty()) {
          if (payTypesBuilder_.isEmpty()) {
            payTypesBuilder_.dispose();
            payTypesBuilder_ = null;
            payTypes_ = other.payTypes_;
            bitField0_ = (bitField0_ & ~0x00000002);
            payTypesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPayTypesFieldBuilder() : null;
          } else {
            payTypesBuilder_.addAllMessages(other.payTypes_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xingyun.policy.api.model.PayRuleDetailItem parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xingyun.policy.api.model.PayRuleDetailItem) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.xingyun.policy.api.model.PayRuleItem.SettingItem settings_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xingyun.policy.api.model.PayRuleItem.SettingItem, com.xingyun.policy.api.model.PayRuleItem.SettingItem.Builder, com.xingyun.policy.api.model.PayRuleItem.SettingItemOrBuilder> settingsBuilder_;
    /**
     * <pre>
     * 支付规则基本信息.
     * </pre>
     *
     * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
     */
    public boolean hasSettings() {
      return settingsBuilder_ != null || settings_ != null;
    }
    /**
     * <pre>
     * 支付规则基本信息.
     * </pre>
     *
     * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
     */
    public com.xingyun.policy.api.model.PayRuleItem.SettingItem getSettings() {
      if (settingsBuilder_ == null) {
        return settings_ == null ? com.xingyun.policy.api.model.PayRuleItem.SettingItem.getDefaultInstance() : settings_;
      } else {
        return settingsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 支付规则基本信息.
     * </pre>
     *
     * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
     */
    public Builder setSettings(com.xingyun.policy.api.model.PayRuleItem.SettingItem value) {
      if (settingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        settings_ = value;
        onChanged();
      } else {
        settingsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 支付规则基本信息.
     * </pre>
     *
     * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
     */
    public Builder setSettings(
        com.xingyun.policy.api.model.PayRuleItem.SettingItem.Builder builderForValue) {
      if (settingsBuilder_ == null) {
        settings_ = builderForValue.build();
        onChanged();
      } else {
        settingsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 支付规则基本信息.
     * </pre>
     *
     * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
     */
    public Builder mergeSettings(com.xingyun.policy.api.model.PayRuleItem.SettingItem value) {
      if (settingsBuilder_ == null) {
        if (settings_ != null) {
          settings_ =
            com.xingyun.policy.api.model.PayRuleItem.SettingItem.newBuilder(settings_).mergeFrom(value).buildPartial();
        } else {
          settings_ = value;
        }
        onChanged();
      } else {
        settingsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 支付规则基本信息.
     * </pre>
     *
     * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
     */
    public Builder clearSettings() {
      if (settingsBuilder_ == null) {
        settings_ = null;
        onChanged();
      } else {
        settings_ = null;
        settingsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 支付规则基本信息.
     * </pre>
     *
     * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
     */
    public com.xingyun.policy.api.model.PayRuleItem.SettingItem.Builder getSettingsBuilder() {
      
      onChanged();
      return getSettingsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 支付规则基本信息.
     * </pre>
     *
     * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
     */
    public com.xingyun.policy.api.model.PayRuleItem.SettingItemOrBuilder getSettingsOrBuilder() {
      if (settingsBuilder_ != null) {
        return settingsBuilder_.getMessageOrBuilder();
      } else {
        return settings_ == null ?
            com.xingyun.policy.api.model.PayRuleItem.SettingItem.getDefaultInstance() : settings_;
      }
    }
    /**
     * <pre>
     * 支付规则基本信息.
     * </pre>
     *
     * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xingyun.policy.api.model.PayRuleItem.SettingItem, com.xingyun.policy.api.model.PayRuleItem.SettingItem.Builder, com.xingyun.policy.api.model.PayRuleItem.SettingItemOrBuilder> 
        getSettingsFieldBuilder() {
      if (settingsBuilder_ == null) {
        settingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xingyun.policy.api.model.PayRuleItem.SettingItem, com.xingyun.policy.api.model.PayRuleItem.SettingItem.Builder, com.xingyun.policy.api.model.PayRuleItem.SettingItemOrBuilder>(
                getSettings(),
                getParentForChildren(),
                isClean());
        settings_ = null;
      }
      return settingsBuilder_;
    }

    private java.util.List<com.xingyun.policy.api.model.PayRuleItem.PayTypeItem> payTypes_ =
      java.util.Collections.emptyList();
    private void ensurePayTypesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        payTypes_ = new java.util.ArrayList<com.xingyun.policy.api.model.PayRuleItem.PayTypeItem>(payTypes_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xingyun.policy.api.model.PayRuleItem.PayTypeItem, com.xingyun.policy.api.model.PayRuleItem.PayTypeItem.Builder, com.xingyun.policy.api.model.PayRuleItem.PayTypeItemOrBuilder> payTypesBuilder_;

    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public java.util.List<com.xingyun.policy.api.model.PayRuleItem.PayTypeItem> getPayTypesList() {
      if (payTypesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(payTypes_);
      } else {
        return payTypesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public int getPayTypesCount() {
      if (payTypesBuilder_ == null) {
        return payTypes_.size();
      } else {
        return payTypesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public com.xingyun.policy.api.model.PayRuleItem.PayTypeItem getPayTypes(int index) {
      if (payTypesBuilder_ == null) {
        return payTypes_.get(index);
      } else {
        return payTypesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public Builder setPayTypes(
        int index, com.xingyun.policy.api.model.PayRuleItem.PayTypeItem value) {
      if (payTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayTypesIsMutable();
        payTypes_.set(index, value);
        onChanged();
      } else {
        payTypesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public Builder setPayTypes(
        int index, com.xingyun.policy.api.model.PayRuleItem.PayTypeItem.Builder builderForValue) {
      if (payTypesBuilder_ == null) {
        ensurePayTypesIsMutable();
        payTypes_.set(index, builderForValue.build());
        onChanged();
      } else {
        payTypesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public Builder addPayTypes(com.xingyun.policy.api.model.PayRuleItem.PayTypeItem value) {
      if (payTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayTypesIsMutable();
        payTypes_.add(value);
        onChanged();
      } else {
        payTypesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public Builder addPayTypes(
        int index, com.xingyun.policy.api.model.PayRuleItem.PayTypeItem value) {
      if (payTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayTypesIsMutable();
        payTypes_.add(index, value);
        onChanged();
      } else {
        payTypesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public Builder addPayTypes(
        com.xingyun.policy.api.model.PayRuleItem.PayTypeItem.Builder builderForValue) {
      if (payTypesBuilder_ == null) {
        ensurePayTypesIsMutable();
        payTypes_.add(builderForValue.build());
        onChanged();
      } else {
        payTypesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public Builder addPayTypes(
        int index, com.xingyun.policy.api.model.PayRuleItem.PayTypeItem.Builder builderForValue) {
      if (payTypesBuilder_ == null) {
        ensurePayTypesIsMutable();
        payTypes_.add(index, builderForValue.build());
        onChanged();
      } else {
        payTypesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public Builder addAllPayTypes(
        java.lang.Iterable<? extends com.xingyun.policy.api.model.PayRuleItem.PayTypeItem> values) {
      if (payTypesBuilder_ == null) {
        ensurePayTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, payTypes_);
        onChanged();
      } else {
        payTypesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public Builder clearPayTypes() {
      if (payTypesBuilder_ == null) {
        payTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        payTypesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public Builder removePayTypes(int index) {
      if (payTypesBuilder_ == null) {
        ensurePayTypesIsMutable();
        payTypes_.remove(index);
        onChanged();
      } else {
        payTypesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public com.xingyun.policy.api.model.PayRuleItem.PayTypeItem.Builder getPayTypesBuilder(
        int index) {
      return getPayTypesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public com.xingyun.policy.api.model.PayRuleItem.PayTypeItemOrBuilder getPayTypesOrBuilder(
        int index) {
      if (payTypesBuilder_ == null) {
        return payTypes_.get(index);  } else {
        return payTypesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public java.util.List<? extends com.xingyun.policy.api.model.PayRuleItem.PayTypeItemOrBuilder> 
         getPayTypesOrBuilderList() {
      if (payTypesBuilder_ != null) {
        return payTypesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(payTypes_);
      }
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public com.xingyun.policy.api.model.PayRuleItem.PayTypeItem.Builder addPayTypesBuilder() {
      return getPayTypesFieldBuilder().addBuilder(
          com.xingyun.policy.api.model.PayRuleItem.PayTypeItem.getDefaultInstance());
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public com.xingyun.policy.api.model.PayRuleItem.PayTypeItem.Builder addPayTypesBuilder(
        int index) {
      return getPayTypesFieldBuilder().addBuilder(
          index, com.xingyun.policy.api.model.PayRuleItem.PayTypeItem.getDefaultInstance());
    }
    /**
     * <pre>
     * 业务支付方式列表.
     * </pre>
     *
     * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
     */
    public java.util.List<com.xingyun.policy.api.model.PayRuleItem.PayTypeItem.Builder> 
         getPayTypesBuilderList() {
      return getPayTypesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xingyun.policy.api.model.PayRuleItem.PayTypeItem, com.xingyun.policy.api.model.PayRuleItem.PayTypeItem.Builder, com.xingyun.policy.api.model.PayRuleItem.PayTypeItemOrBuilder> 
        getPayTypesFieldBuilder() {
      if (payTypesBuilder_ == null) {
        payTypesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.xingyun.policy.api.model.PayRuleItem.PayTypeItem, com.xingyun.policy.api.model.PayRuleItem.PayTypeItem.Builder, com.xingyun.policy.api.model.PayRuleItem.PayTypeItemOrBuilder>(
                payTypes_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        payTypes_ = null;
      }
      return payTypesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.PayRuleDetailItem)
  }

  // @@protoc_insertion_point(class_scope:api.PayRuleDetailItem)
  private static final com.xingyun.policy.api.model.PayRuleDetailItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xingyun.policy.api.model.PayRuleDetailItem();
  }

  public static com.xingyun.policy.api.model.PayRuleDetailItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PayRuleDetailItem>
      PARSER = new com.google.protobuf.AbstractParser<PayRuleDetailItem>() {
    public PayRuleDetailItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PayRuleDetailItem(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PayRuleDetailItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PayRuleDetailItem> getParserForType() {
    return PARSER;
  }

  public com.xingyun.policy.api.model.PayRuleDetailItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

