// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.xingyun.policy.api.model;

public interface PayRuleDetailItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.PayRuleDetailItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 支付规则基本信息.
   * </pre>
   *
   * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
   */
  boolean hasSettings();
  /**
   * <pre>
   * 支付规则基本信息.
   * </pre>
   *
   * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
   */
  com.xingyun.policy.api.model.PayRuleItem.SettingItem getSettings();
  /**
   * <pre>
   * 支付规则基本信息.
   * </pre>
   *
   * <code>.api.PayRuleItem.SettingItem settings = 1;</code>
   */
  com.xingyun.policy.api.model.PayRuleItem.SettingItemOrBuilder getSettingsOrBuilder();

  /**
   * <pre>
   * 业务支付方式列表.
   * </pre>
   *
   * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
   */
  java.util.List<com.xingyun.policy.api.model.PayRuleItem.PayTypeItem> 
      getPayTypesList();
  /**
   * <pre>
   * 业务支付方式列表.
   * </pre>
   *
   * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
   */
  com.xingyun.policy.api.model.PayRuleItem.PayTypeItem getPayTypes(int index);
  /**
   * <pre>
   * 业务支付方式列表.
   * </pre>
   *
   * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
   */
  int getPayTypesCount();
  /**
   * <pre>
   * 业务支付方式列表.
   * </pre>
   *
   * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
   */
  java.util.List<? extends com.xingyun.policy.api.model.PayRuleItem.PayTypeItemOrBuilder> 
      getPayTypesOrBuilderList();
  /**
   * <pre>
   * 业务支付方式列表.
   * </pre>
   *
   * <code>repeated .api.PayRuleItem.PayTypeItem pay_types = 2;</code>
   */
  com.xingyun.policy.api.model.PayRuleItem.PayTypeItemOrBuilder getPayTypesOrBuilder(
      int index);
}
