// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.xingyun.policy.api.model;

/**
 * <pre>
 * 规则时间信息.
 * </pre>
 *
 * Protobuf type {@code api.TimeItem}
 */
public  final class TimeItem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.TimeItem)
    TimeItemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TimeItem.newBuilder() to construct.
  private TimeItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TimeItem() {
    foreignUuid_ = "";
    dateUuid_ = "";
    timeLimit_ = false;
    monday_ = false;
    tuesday_ = false;
    wednesday_ = false;
    thursday_ = false;
    friday_ = false;
    saturday_ = false;
    sunday_ = false;
    timeRange_ = "";
    timeType_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TimeItem(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            foreignUuid_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            dateUuid_ = s;
            break;
          }
          case 24: {

            timeLimit_ = input.readBool();
            break;
          }
          case 32: {

            monday_ = input.readBool();
            break;
          }
          case 40: {

            tuesday_ = input.readBool();
            break;
          }
          case 48: {

            wednesday_ = input.readBool();
            break;
          }
          case 56: {

            thursday_ = input.readBool();
            break;
          }
          case 64: {

            friday_ = input.readBool();
            break;
          }
          case 72: {

            saturday_ = input.readBool();
            break;
          }
          case 80: {

            sunday_ = input.readBool();
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            timeRange_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            timeType_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xingyun.policy.api.model.Model.internal_static_api_TimeItem_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xingyun.policy.api.model.Model.internal_static_api_TimeItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xingyun.policy.api.model.TimeItem.class, com.xingyun.policy.api.model.TimeItem.Builder.class);
  }

  public static final int FOREIGN_UUID_FIELD_NUMBER = 1;
  private volatile java.lang.Object foreignUuid_;
  /**
   * <pre>
   * 规则UUID.
   * </pre>
   *
   * <code>string foreign_uuid = 1;</code>
   */
  public java.lang.String getForeignUuid() {
    java.lang.Object ref = foreignUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      foreignUuid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 规则UUID.
   * </pre>
   *
   * <code>string foreign_uuid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getForeignUuidBytes() {
    java.lang.Object ref = foreignUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      foreignUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATE_UUID_FIELD_NUMBER = 2;
  private volatile java.lang.Object dateUuid_;
  /**
   * <pre>
   * 时间规则对应UUID.
   * </pre>
   *
   * <code>string date_uuid = 2;</code>
   */
  public java.lang.String getDateUuid() {
    java.lang.Object ref = dateUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dateUuid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 时间规则对应UUID.
   * </pre>
   *
   * <code>string date_uuid = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDateUuidBytes() {
    java.lang.Object ref = dateUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dateUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_LIMIT_FIELD_NUMBER = 3;
  private boolean timeLimit_;
  /**
   * <pre>
   *是否启用时间限制(1:启用 0：不启用).
   * </pre>
   *
   * <code>bool time_limit = 3;</code>
   */
  public boolean getTimeLimit() {
    return timeLimit_;
  }

  public static final int MONDAY_FIELD_NUMBER = 4;
  private boolean monday_;
  /**
   * <pre>
   * 周一是否允许.
   * </pre>
   *
   * <code>bool monday = 4;</code>
   */
  public boolean getMonday() {
    return monday_;
  }

  public static final int TUESDAY_FIELD_NUMBER = 5;
  private boolean tuesday_;
  /**
   * <pre>
   * 周二是否允许.
   * </pre>
   *
   * <code>bool tuesday = 5;</code>
   */
  public boolean getTuesday() {
    return tuesday_;
  }

  public static final int WEDNESDAY_FIELD_NUMBER = 6;
  private boolean wednesday_;
  /**
   * <pre>
   * 周三是否允许.
   * </pre>
   *
   * <code>bool wednesday = 6;</code>
   */
  public boolean getWednesday() {
    return wednesday_;
  }

  public static final int THURSDAY_FIELD_NUMBER = 7;
  private boolean thursday_;
  /**
   * <pre>
   * 周四是否允许.
   * </pre>
   *
   * <code>bool thursday = 7;</code>
   */
  public boolean getThursday() {
    return thursday_;
  }

  public static final int FRIDAY_FIELD_NUMBER = 8;
  private boolean friday_;
  /**
   * <pre>
   * 周五是否允许.
   * </pre>
   *
   * <code>bool friday = 8;</code>
   */
  public boolean getFriday() {
    return friday_;
  }

  public static final int SATURDAY_FIELD_NUMBER = 9;
  private boolean saturday_;
  /**
   * <pre>
   * 周六是否允许.
   * </pre>
   *
   * <code>bool saturday = 9;</code>
   */
  public boolean getSaturday() {
    return saturday_;
  }

  public static final int SUNDAY_FIELD_NUMBER = 10;
  private boolean sunday_;
  /**
   * <pre>
   * 周日是否允许.
   * </pre>
   *
   * <code>bool sunday = 10;</code>
   */
  public boolean getSunday() {
    return sunday_;
  }

  public static final int TIME_RANGE_FIELD_NUMBER = 11;
  private volatile java.lang.Object timeRange_;
  /**
   * <pre>
   * 时间段范围（多个时间段用#隔开，每个时间段中间用“|”号隔开，如0630|2135#1225|2210）.
   * </pre>
   *
   * <code>string time_range = 11;</code>
   */
  public java.lang.String getTimeRange() {
    java.lang.Object ref = timeRange_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeRange_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 时间段范围（多个时间段用#隔开，每个时间段中间用“|”号隔开，如0630|2135#1225|2210）.
   * </pre>
   *
   * <code>string time_range = 11;</code>
   */
  public com.google.protobuf.ByteString
      getTimeRangeBytes() {
    java.lang.Object ref = timeRange_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeRange_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_TYPE_FIELD_NUMBER = 12;
  private volatile java.lang.Object timeType_;
  /**
   * <pre>
   *时间类型（1：出发时间 2：接机 3：送机 4：接站 5：送站）.
   * </pre>
   *
   * <code>string time_type = 12;</code>
   */
  public java.lang.String getTimeType() {
    java.lang.Object ref = timeType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *时间类型（1：出发时间 2：接机 3：送机 4：接站 5：送站）.
   * </pre>
   *
   * <code>string time_type = 12;</code>
   */
  public com.google.protobuf.ByteString
      getTimeTypeBytes() {
    java.lang.Object ref = timeType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getForeignUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, foreignUuid_);
    }
    if (!getDateUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dateUuid_);
    }
    if (timeLimit_ != false) {
      output.writeBool(3, timeLimit_);
    }
    if (monday_ != false) {
      output.writeBool(4, monday_);
    }
    if (tuesday_ != false) {
      output.writeBool(5, tuesday_);
    }
    if (wednesday_ != false) {
      output.writeBool(6, wednesday_);
    }
    if (thursday_ != false) {
      output.writeBool(7, thursday_);
    }
    if (friday_ != false) {
      output.writeBool(8, friday_);
    }
    if (saturday_ != false) {
      output.writeBool(9, saturday_);
    }
    if (sunday_ != false) {
      output.writeBool(10, sunday_);
    }
    if (!getTimeRangeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, timeRange_);
    }
    if (!getTimeTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, timeType_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getForeignUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, foreignUuid_);
    }
    if (!getDateUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dateUuid_);
    }
    if (timeLimit_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, timeLimit_);
    }
    if (monday_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, monday_);
    }
    if (tuesday_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, tuesday_);
    }
    if (wednesday_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, wednesday_);
    }
    if (thursday_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, thursday_);
    }
    if (friday_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, friday_);
    }
    if (saturday_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, saturday_);
    }
    if (sunday_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, sunday_);
    }
    if (!getTimeRangeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, timeRange_);
    }
    if (!getTimeTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, timeType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xingyun.policy.api.model.TimeItem)) {
      return super.equals(obj);
    }
    com.xingyun.policy.api.model.TimeItem other = (com.xingyun.policy.api.model.TimeItem) obj;

    boolean result = true;
    result = result && getForeignUuid()
        .equals(other.getForeignUuid());
    result = result && getDateUuid()
        .equals(other.getDateUuid());
    result = result && (getTimeLimit()
        == other.getTimeLimit());
    result = result && (getMonday()
        == other.getMonday());
    result = result && (getTuesday()
        == other.getTuesday());
    result = result && (getWednesday()
        == other.getWednesday());
    result = result && (getThursday()
        == other.getThursday());
    result = result && (getFriday()
        == other.getFriday());
    result = result && (getSaturday()
        == other.getSaturday());
    result = result && (getSunday()
        == other.getSunday());
    result = result && getTimeRange()
        .equals(other.getTimeRange());
    result = result && getTimeType()
        .equals(other.getTimeType());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FOREIGN_UUID_FIELD_NUMBER;
    hash = (53 * hash) + getForeignUuid().hashCode();
    hash = (37 * hash) + DATE_UUID_FIELD_NUMBER;
    hash = (53 * hash) + getDateUuid().hashCode();
    hash = (37 * hash) + TIME_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTimeLimit());
    hash = (37 * hash) + MONDAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMonday());
    hash = (37 * hash) + TUESDAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTuesday());
    hash = (37 * hash) + WEDNESDAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWednesday());
    hash = (37 * hash) + THURSDAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getThursday());
    hash = (37 * hash) + FRIDAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFriday());
    hash = (37 * hash) + SATURDAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSaturday());
    hash = (37 * hash) + SUNDAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSunday());
    hash = (37 * hash) + TIME_RANGE_FIELD_NUMBER;
    hash = (53 * hash) + getTimeRange().hashCode();
    hash = (37 * hash) + TIME_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTimeType().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xingyun.policy.api.model.TimeItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.model.TimeItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.TimeItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.model.TimeItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.TimeItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.model.TimeItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.TimeItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.model.TimeItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.TimeItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.model.TimeItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.TimeItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.model.TimeItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xingyun.policy.api.model.TimeItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 规则时间信息.
   * </pre>
   *
   * Protobuf type {@code api.TimeItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.TimeItem)
      com.xingyun.policy.api.model.TimeItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xingyun.policy.api.model.Model.internal_static_api_TimeItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xingyun.policy.api.model.Model.internal_static_api_TimeItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xingyun.policy.api.model.TimeItem.class, com.xingyun.policy.api.model.TimeItem.Builder.class);
    }

    // Construct using com.xingyun.policy.api.model.TimeItem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      foreignUuid_ = "";

      dateUuid_ = "";

      timeLimit_ = false;

      monday_ = false;

      tuesday_ = false;

      wednesday_ = false;

      thursday_ = false;

      friday_ = false;

      saturday_ = false;

      sunday_ = false;

      timeRange_ = "";

      timeType_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xingyun.policy.api.model.Model.internal_static_api_TimeItem_descriptor;
    }

    public com.xingyun.policy.api.model.TimeItem getDefaultInstanceForType() {
      return com.xingyun.policy.api.model.TimeItem.getDefaultInstance();
    }

    public com.xingyun.policy.api.model.TimeItem build() {
      com.xingyun.policy.api.model.TimeItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.xingyun.policy.api.model.TimeItem buildPartial() {
      com.xingyun.policy.api.model.TimeItem result = new com.xingyun.policy.api.model.TimeItem(this);
      result.foreignUuid_ = foreignUuid_;
      result.dateUuid_ = dateUuid_;
      result.timeLimit_ = timeLimit_;
      result.monday_ = monday_;
      result.tuesday_ = tuesday_;
      result.wednesday_ = wednesday_;
      result.thursday_ = thursday_;
      result.friday_ = friday_;
      result.saturday_ = saturday_;
      result.sunday_ = sunday_;
      result.timeRange_ = timeRange_;
      result.timeType_ = timeType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xingyun.policy.api.model.TimeItem) {
        return mergeFrom((com.xingyun.policy.api.model.TimeItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xingyun.policy.api.model.TimeItem other) {
      if (other == com.xingyun.policy.api.model.TimeItem.getDefaultInstance()) return this;
      if (!other.getForeignUuid().isEmpty()) {
        foreignUuid_ = other.foreignUuid_;
        onChanged();
      }
      if (!other.getDateUuid().isEmpty()) {
        dateUuid_ = other.dateUuid_;
        onChanged();
      }
      if (other.getTimeLimit() != false) {
        setTimeLimit(other.getTimeLimit());
      }
      if (other.getMonday() != false) {
        setMonday(other.getMonday());
      }
      if (other.getTuesday() != false) {
        setTuesday(other.getTuesday());
      }
      if (other.getWednesday() != false) {
        setWednesday(other.getWednesday());
      }
      if (other.getThursday() != false) {
        setThursday(other.getThursday());
      }
      if (other.getFriday() != false) {
        setFriday(other.getFriday());
      }
      if (other.getSaturday() != false) {
        setSaturday(other.getSaturday());
      }
      if (other.getSunday() != false) {
        setSunday(other.getSunday());
      }
      if (!other.getTimeRange().isEmpty()) {
        timeRange_ = other.timeRange_;
        onChanged();
      }
      if (!other.getTimeType().isEmpty()) {
        timeType_ = other.timeType_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xingyun.policy.api.model.TimeItem parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xingyun.policy.api.model.TimeItem) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object foreignUuid_ = "";
    /**
     * <pre>
     * 规则UUID.
     * </pre>
     *
     * <code>string foreign_uuid = 1;</code>
     */
    public java.lang.String getForeignUuid() {
      java.lang.Object ref = foreignUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        foreignUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 规则UUID.
     * </pre>
     *
     * <code>string foreign_uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getForeignUuidBytes() {
      java.lang.Object ref = foreignUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        foreignUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 规则UUID.
     * </pre>
     *
     * <code>string foreign_uuid = 1;</code>
     */
    public Builder setForeignUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      foreignUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 规则UUID.
     * </pre>
     *
     * <code>string foreign_uuid = 1;</code>
     */
    public Builder clearForeignUuid() {
      
      foreignUuid_ = getDefaultInstance().getForeignUuid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 规则UUID.
     * </pre>
     *
     * <code>string foreign_uuid = 1;</code>
     */
    public Builder setForeignUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      foreignUuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dateUuid_ = "";
    /**
     * <pre>
     * 时间规则对应UUID.
     * </pre>
     *
     * <code>string date_uuid = 2;</code>
     */
    public java.lang.String getDateUuid() {
      java.lang.Object ref = dateUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 时间规则对应UUID.
     * </pre>
     *
     * <code>string date_uuid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDateUuidBytes() {
      java.lang.Object ref = dateUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 时间规则对应UUID.
     * </pre>
     *
     * <code>string date_uuid = 2;</code>
     */
    public Builder setDateUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dateUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间规则对应UUID.
     * </pre>
     *
     * <code>string date_uuid = 2;</code>
     */
    public Builder clearDateUuid() {
      
      dateUuid_ = getDefaultInstance().getDateUuid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间规则对应UUID.
     * </pre>
     *
     * <code>string date_uuid = 2;</code>
     */
    public Builder setDateUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dateUuid_ = value;
      onChanged();
      return this;
    }

    private boolean timeLimit_ ;
    /**
     * <pre>
     *是否启用时间限制(1:启用 0：不启用).
     * </pre>
     *
     * <code>bool time_limit = 3;</code>
     */
    public boolean getTimeLimit() {
      return timeLimit_;
    }
    /**
     * <pre>
     *是否启用时间限制(1:启用 0：不启用).
     * </pre>
     *
     * <code>bool time_limit = 3;</code>
     */
    public Builder setTimeLimit(boolean value) {
      
      timeLimit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *是否启用时间限制(1:启用 0：不启用).
     * </pre>
     *
     * <code>bool time_limit = 3;</code>
     */
    public Builder clearTimeLimit() {
      
      timeLimit_ = false;
      onChanged();
      return this;
    }

    private boolean monday_ ;
    /**
     * <pre>
     * 周一是否允许.
     * </pre>
     *
     * <code>bool monday = 4;</code>
     */
    public boolean getMonday() {
      return monday_;
    }
    /**
     * <pre>
     * 周一是否允许.
     * </pre>
     *
     * <code>bool monday = 4;</code>
     */
    public Builder setMonday(boolean value) {
      
      monday_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 周一是否允许.
     * </pre>
     *
     * <code>bool monday = 4;</code>
     */
    public Builder clearMonday() {
      
      monday_ = false;
      onChanged();
      return this;
    }

    private boolean tuesday_ ;
    /**
     * <pre>
     * 周二是否允许.
     * </pre>
     *
     * <code>bool tuesday = 5;</code>
     */
    public boolean getTuesday() {
      return tuesday_;
    }
    /**
     * <pre>
     * 周二是否允许.
     * </pre>
     *
     * <code>bool tuesday = 5;</code>
     */
    public Builder setTuesday(boolean value) {
      
      tuesday_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 周二是否允许.
     * </pre>
     *
     * <code>bool tuesday = 5;</code>
     */
    public Builder clearTuesday() {
      
      tuesday_ = false;
      onChanged();
      return this;
    }

    private boolean wednesday_ ;
    /**
     * <pre>
     * 周三是否允许.
     * </pre>
     *
     * <code>bool wednesday = 6;</code>
     */
    public boolean getWednesday() {
      return wednesday_;
    }
    /**
     * <pre>
     * 周三是否允许.
     * </pre>
     *
     * <code>bool wednesday = 6;</code>
     */
    public Builder setWednesday(boolean value) {
      
      wednesday_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 周三是否允许.
     * </pre>
     *
     * <code>bool wednesday = 6;</code>
     */
    public Builder clearWednesday() {
      
      wednesday_ = false;
      onChanged();
      return this;
    }

    private boolean thursday_ ;
    /**
     * <pre>
     * 周四是否允许.
     * </pre>
     *
     * <code>bool thursday = 7;</code>
     */
    public boolean getThursday() {
      return thursday_;
    }
    /**
     * <pre>
     * 周四是否允许.
     * </pre>
     *
     * <code>bool thursday = 7;</code>
     */
    public Builder setThursday(boolean value) {
      
      thursday_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 周四是否允许.
     * </pre>
     *
     * <code>bool thursday = 7;</code>
     */
    public Builder clearThursday() {
      
      thursday_ = false;
      onChanged();
      return this;
    }

    private boolean friday_ ;
    /**
     * <pre>
     * 周五是否允许.
     * </pre>
     *
     * <code>bool friday = 8;</code>
     */
    public boolean getFriday() {
      return friday_;
    }
    /**
     * <pre>
     * 周五是否允许.
     * </pre>
     *
     * <code>bool friday = 8;</code>
     */
    public Builder setFriday(boolean value) {
      
      friday_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 周五是否允许.
     * </pre>
     *
     * <code>bool friday = 8;</code>
     */
    public Builder clearFriday() {
      
      friday_ = false;
      onChanged();
      return this;
    }

    private boolean saturday_ ;
    /**
     * <pre>
     * 周六是否允许.
     * </pre>
     *
     * <code>bool saturday = 9;</code>
     */
    public boolean getSaturday() {
      return saturday_;
    }
    /**
     * <pre>
     * 周六是否允许.
     * </pre>
     *
     * <code>bool saturday = 9;</code>
     */
    public Builder setSaturday(boolean value) {
      
      saturday_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 周六是否允许.
     * </pre>
     *
     * <code>bool saturday = 9;</code>
     */
    public Builder clearSaturday() {
      
      saturday_ = false;
      onChanged();
      return this;
    }

    private boolean sunday_ ;
    /**
     * <pre>
     * 周日是否允许.
     * </pre>
     *
     * <code>bool sunday = 10;</code>
     */
    public boolean getSunday() {
      return sunday_;
    }
    /**
     * <pre>
     * 周日是否允许.
     * </pre>
     *
     * <code>bool sunday = 10;</code>
     */
    public Builder setSunday(boolean value) {
      
      sunday_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 周日是否允许.
     * </pre>
     *
     * <code>bool sunday = 10;</code>
     */
    public Builder clearSunday() {
      
      sunday_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object timeRange_ = "";
    /**
     * <pre>
     * 时间段范围（多个时间段用#隔开，每个时间段中间用“|”号隔开，如0630|2135#1225|2210）.
     * </pre>
     *
     * <code>string time_range = 11;</code>
     */
    public java.lang.String getTimeRange() {
      java.lang.Object ref = timeRange_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeRange_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 时间段范围（多个时间段用#隔开，每个时间段中间用“|”号隔开，如0630|2135#1225|2210）.
     * </pre>
     *
     * <code>string time_range = 11;</code>
     */
    public com.google.protobuf.ByteString
        getTimeRangeBytes() {
      java.lang.Object ref = timeRange_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeRange_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 时间段范围（多个时间段用#隔开，每个时间段中间用“|”号隔开，如0630|2135#1225|2210）.
     * </pre>
     *
     * <code>string time_range = 11;</code>
     */
    public Builder setTimeRange(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeRange_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间段范围（多个时间段用#隔开，每个时间段中间用“|”号隔开，如0630|2135#1225|2210）.
     * </pre>
     *
     * <code>string time_range = 11;</code>
     */
    public Builder clearTimeRange() {
      
      timeRange_ = getDefaultInstance().getTimeRange();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间段范围（多个时间段用#隔开，每个时间段中间用“|”号隔开，如0630|2135#1225|2210）.
     * </pre>
     *
     * <code>string time_range = 11;</code>
     */
    public Builder setTimeRangeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeRange_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object timeType_ = "";
    /**
     * <pre>
     *时间类型（1：出发时间 2：接机 3：送机 4：接站 5：送站）.
     * </pre>
     *
     * <code>string time_type = 12;</code>
     */
    public java.lang.String getTimeType() {
      java.lang.Object ref = timeType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *时间类型（1：出发时间 2：接机 3：送机 4：接站 5：送站）.
     * </pre>
     *
     * <code>string time_type = 12;</code>
     */
    public com.google.protobuf.ByteString
        getTimeTypeBytes() {
      java.lang.Object ref = timeType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *时间类型（1：出发时间 2：接机 3：送机 4：接站 5：送站）.
     * </pre>
     *
     * <code>string time_type = 12;</code>
     */
    public Builder setTimeType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *时间类型（1：出发时间 2：接机 3：送机 4：接站 5：送站）.
     * </pre>
     *
     * <code>string time_type = 12;</code>
     */
    public Builder clearTimeType() {
      
      timeType_ = getDefaultInstance().getTimeType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *时间类型（1：出发时间 2：接机 3：送机 4：接站 5：送站）.
     * </pre>
     *
     * <code>string time_type = 12;</code>
     */
    public Builder setTimeTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeType_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.TimeItem)
  }

  // @@protoc_insertion_point(class_scope:api.TimeItem)
  private static final com.xingyun.policy.api.model.TimeItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xingyun.policy.api.model.TimeItem();
  }

  public static com.xingyun.policy.api.model.TimeItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TimeItem>
      PARSER = new com.google.protobuf.AbstractParser<TimeItem>() {
    public TimeItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TimeItem(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TimeItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TimeItem> getParserForType() {
    return PARSER;
  }

  public com.xingyun.policy.api.model.TimeItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

