// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.xingyun.policy.api.model;

public interface TimeItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.TimeItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 规则UUID.
   * </pre>
   *
   * <code>string foreign_uuid = 1;</code>
   */
  java.lang.String getForeignUuid();
  /**
   * <pre>
   * 规则UUID.
   * </pre>
   *
   * <code>string foreign_uuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getForeignUuidBytes();

  /**
   * <pre>
   * 时间规则对应UUID.
   * </pre>
   *
   * <code>string date_uuid = 2;</code>
   */
  java.lang.String getDateUuid();
  /**
   * <pre>
   * 时间规则对应UUID.
   * </pre>
   *
   * <code>string date_uuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateUuidBytes();

  /**
   * <pre>
   *是否启用时间限制(1:启用 0：不启用).
   * </pre>
   *
   * <code>bool time_limit = 3;</code>
   */
  boolean getTimeLimit();

  /**
   * <pre>
   * 周一是否允许.
   * </pre>
   *
   * <code>bool monday = 4;</code>
   */
  boolean getMonday();

  /**
   * <pre>
   * 周二是否允许.
   * </pre>
   *
   * <code>bool tuesday = 5;</code>
   */
  boolean getTuesday();

  /**
   * <pre>
   * 周三是否允许.
   * </pre>
   *
   * <code>bool wednesday = 6;</code>
   */
  boolean getWednesday();

  /**
   * <pre>
   * 周四是否允许.
   * </pre>
   *
   * <code>bool thursday = 7;</code>
   */
  boolean getThursday();

  /**
   * <pre>
   * 周五是否允许.
   * </pre>
   *
   * <code>bool friday = 8;</code>
   */
  boolean getFriday();

  /**
   * <pre>
   * 周六是否允许.
   * </pre>
   *
   * <code>bool saturday = 9;</code>
   */
  boolean getSaturday();

  /**
   * <pre>
   * 周日是否允许.
   * </pre>
   *
   * <code>bool sunday = 10;</code>
   */
  boolean getSunday();

  /**
   * <pre>
   * 时间段范围（多个时间段用#隔开，每个时间段中间用“|”号隔开，如0630|2135#1225|2210）.
   * </pre>
   *
   * <code>string time_range = 11;</code>
   */
  java.lang.String getTimeRange();
  /**
   * <pre>
   * 时间段范围（多个时间段用#隔开，每个时间段中间用“|”号隔开，如0630|2135#1225|2210）.
   * </pre>
   *
   * <code>string time_range = 11;</code>
   */
  com.google.protobuf.ByteString
      getTimeRangeBytes();

  /**
   * <pre>
   *时间类型（1：出发时间 2：接机 3：送机 4：接站 5：送站）.
   * </pre>
   *
   * <code>string time_type = 12;</code>
   */
  java.lang.String getTimeType();
  /**
   * <pre>
   *时间类型（1：出发时间 2：接机 3：送机 4：接站 5：送站）.
   * </pre>
   *
   * <code>string time_type = 12;</code>
   */
  com.google.protobuf.ByteString
      getTimeTypeBytes();
}
