// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.xingyun.policy.api.model;

/**
 * <pre>
 * 火车规则详情封装.
 * </pre>
 *
 * Protobuf type {@code api.TrainRuleDetailItem}
 */
public  final class TrainRuleDetailItem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.TrainRuleDetailItem)
    TrainRuleDetailItemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrainRuleDetailItem.newBuilder() to construct.
  private TrainRuleDetailItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrainRuleDetailItem() {
    times_ = java.util.Collections.emptyList();
    canUse_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TrainRuleDetailItem(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.xingyun.policy.api.model.TrainRuleItem.SettingItem.Builder subBuilder = null;
            if (settings_ != null) {
              subBuilder = settings_.toBuilder();
            }
            settings_ = input.readMessage(com.xingyun.policy.api.model.TrainRuleItem.SettingItem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(settings_);
              settings_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              times_ = new java.util.ArrayList<com.xingyun.policy.api.model.TimeItem>();
              mutable_bitField0_ |= 0x00000002;
            }
            times_.add(
                input.readMessage(com.xingyun.policy.api.model.TimeItem.parser(), extensionRegistry));
            break;
          }
          case 80: {

            canUse_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        times_ = java.util.Collections.unmodifiableList(times_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xingyun.policy.api.model.Model.internal_static_api_TrainRuleDetailItem_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xingyun.policy.api.model.Model.internal_static_api_TrainRuleDetailItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xingyun.policy.api.model.TrainRuleDetailItem.class, com.xingyun.policy.api.model.TrainRuleDetailItem.Builder.class);
  }

  private int bitField0_;
  public static final int SETTINGS_FIELD_NUMBER = 1;
  private com.xingyun.policy.api.model.TrainRuleItem.SettingItem settings_;
  /**
   * <pre>
   * 火车票规则基本信息.
   * </pre>
   *
   * <code>.api.TrainRuleItem.SettingItem settings = 1;</code>
   */
  public boolean hasSettings() {
    return settings_ != null;
  }
  /**
   * <pre>
   * 火车票规则基本信息.
   * </pre>
   *
   * <code>.api.TrainRuleItem.SettingItem settings = 1;</code>
   */
  public com.xingyun.policy.api.model.TrainRuleItem.SettingItem getSettings() {
    return settings_ == null ? com.xingyun.policy.api.model.TrainRuleItem.SettingItem.getDefaultInstance() : settings_;
  }
  /**
   * <pre>
   * 火车票规则基本信息.
   * </pre>
   *
   * <code>.api.TrainRuleItem.SettingItem settings = 1;</code>
   */
  public com.xingyun.policy.api.model.TrainRuleItem.SettingItemOrBuilder getSettingsOrBuilder() {
    return getSettings();
  }

  public static final int TIMES_FIELD_NUMBER = 2;
  private java.util.List<com.xingyun.policy.api.model.TimeItem> times_;
  /**
   * <pre>
   * 时间限制信息.
   * </pre>
   *
   * <code>repeated .api.TimeItem times = 2;</code>
   */
  public java.util.List<com.xingyun.policy.api.model.TimeItem> getTimesList() {
    return times_;
  }
  /**
   * <pre>
   * 时间限制信息.
   * </pre>
   *
   * <code>repeated .api.TimeItem times = 2;</code>
   */
  public java.util.List<? extends com.xingyun.policy.api.model.TimeItemOrBuilder> 
      getTimesOrBuilderList() {
    return times_;
  }
  /**
   * <pre>
   * 时间限制信息.
   * </pre>
   *
   * <code>repeated .api.TimeItem times = 2;</code>
   */
  public int getTimesCount() {
    return times_.size();
  }
  /**
   * <pre>
   * 时间限制信息.
   * </pre>
   *
   * <code>repeated .api.TimeItem times = 2;</code>
   */
  public com.xingyun.policy.api.model.TimeItem getTimes(int index) {
    return times_.get(index);
  }
  /**
   * <pre>
   * 时间限制信息.
   * </pre>
   *
   * <code>repeated .api.TimeItem times = 2;</code>
   */
  public com.xingyun.policy.api.model.TimeItemOrBuilder getTimesOrBuilder(
      int index) {
    return times_.get(index);
  }

  public static final int CAN_USE_FIELD_NUMBER = 10;
  private int canUse_;
  /**
   * <pre>
   * 是否可用 (0:不可用 1:可用有政策 2:可用无政策).
   * </pre>
   *
   * <code>int32 can_use = 10;</code>
   */
  public int getCanUse() {
    return canUse_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (settings_ != null) {
      output.writeMessage(1, getSettings());
    }
    for (int i = 0; i < times_.size(); i++) {
      output.writeMessage(2, times_.get(i));
    }
    if (canUse_ != 0) {
      output.writeInt32(10, canUse_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (settings_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSettings());
    }
    for (int i = 0; i < times_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, times_.get(i));
    }
    if (canUse_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, canUse_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xingyun.policy.api.model.TrainRuleDetailItem)) {
      return super.equals(obj);
    }
    com.xingyun.policy.api.model.TrainRuleDetailItem other = (com.xingyun.policy.api.model.TrainRuleDetailItem) obj;

    boolean result = true;
    result = result && (hasSettings() == other.hasSettings());
    if (hasSettings()) {
      result = result && getSettings()
          .equals(other.getSettings());
    }
    result = result && getTimesList()
        .equals(other.getTimesList());
    result = result && (getCanUse()
        == other.getCanUse());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSettings()) {
      hash = (37 * hash) + SETTINGS_FIELD_NUMBER;
      hash = (53 * hash) + getSettings().hashCode();
    }
    if (getTimesCount() > 0) {
      hash = (37 * hash) + TIMES_FIELD_NUMBER;
      hash = (53 * hash) + getTimesList().hashCode();
    }
    hash = (37 * hash) + CAN_USE_FIELD_NUMBER;
    hash = (53 * hash) + getCanUse();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xingyun.policy.api.model.TrainRuleDetailItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.model.TrainRuleDetailItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.TrainRuleDetailItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.model.TrainRuleDetailItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.TrainRuleDetailItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.model.TrainRuleDetailItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.TrainRuleDetailItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.model.TrainRuleDetailItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.TrainRuleDetailItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.model.TrainRuleDetailItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xingyun.policy.api.model.TrainRuleDetailItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.model.TrainRuleDetailItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xingyun.policy.api.model.TrainRuleDetailItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 火车规则详情封装.
   * </pre>
   *
   * Protobuf type {@code api.TrainRuleDetailItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.TrainRuleDetailItem)
      com.xingyun.policy.api.model.TrainRuleDetailItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xingyun.policy.api.model.Model.internal_static_api_TrainRuleDetailItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xingyun.policy.api.model.Model.internal_static_api_TrainRuleDetailItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xingyun.policy.api.model.TrainRuleDetailItem.class, com.xingyun.policy.api.model.TrainRuleDetailItem.Builder.class);
    }

    // Construct using com.xingyun.policy.api.model.TrainRuleDetailItem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTimesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (settingsBuilder_ == null) {
        settings_ = null;
      } else {
        settings_ = null;
        settingsBuilder_ = null;
      }
      if (timesBuilder_ == null) {
        times_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        timesBuilder_.clear();
      }
      canUse_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xingyun.policy.api.model.Model.internal_static_api_TrainRuleDetailItem_descriptor;
    }

    public com.xingyun.policy.api.model.TrainRuleDetailItem getDefaultInstanceForType() {
      return com.xingyun.policy.api.model.TrainRuleDetailItem.getDefaultInstance();
    }

    public com.xingyun.policy.api.model.TrainRuleDetailItem build() {
      com.xingyun.policy.api.model.TrainRuleDetailItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.xingyun.policy.api.model.TrainRuleDetailItem buildPartial() {
      com.xingyun.policy.api.model.TrainRuleDetailItem result = new com.xingyun.policy.api.model.TrainRuleDetailItem(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (settingsBuilder_ == null) {
        result.settings_ = settings_;
      } else {
        result.settings_ = settingsBuilder_.build();
      }
      if (timesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          times_ = java.util.Collections.unmodifiableList(times_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.times_ = times_;
      } else {
        result.times_ = timesBuilder_.build();
      }
      result.canUse_ = canUse_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xingyun.policy.api.model.TrainRuleDetailItem) {
        return mergeFrom((com.xingyun.policy.api.model.TrainRuleDetailItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xingyun.policy.api.model.TrainRuleDetailItem other) {
      if (other == com.xingyun.policy.api.model.TrainRuleDetailItem.getDefaultInstance()) return this;
      if (other.hasSettings()) {
        mergeSettings(other.getSettings());
      }
      if (timesBuilder_ == null) {
        if (!other.times_.isEmpty()) {
          if (times_.isEmpty()) {
            times_ = other.times_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTimesIsMutable();
            times_.addAll(other.times_);
          }
          onChanged();
        }
      } else {
        if (!other.times_.isEmpty()) {
          if (timesBuilder_.isEmpty()) {
            timesBuilder_.dispose();
            timesBuilder_ = null;
            times_ = other.times_;
            bitField0_ = (bitField0_ & ~0x00000002);
            timesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTimesFieldBuilder() : null;
          } else {
            timesBuilder_.addAllMessages(other.times_);
          }
        }
      }
      if (other.getCanUse() != 0) {
        setCanUse(other.getCanUse());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xingyun.policy.api.model.TrainRuleDetailItem parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xingyun.policy.api.model.TrainRuleDetailItem) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.xingyun.policy.api.model.TrainRuleItem.SettingItem settings_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xingyun.policy.api.model.TrainRuleItem.SettingItem, com.xingyun.policy.api.model.TrainRuleItem.SettingItem.Builder, com.xingyun.policy.api.model.TrainRuleItem.SettingItemOrBuilder> settingsBuilder_;
    /**
     * <pre>
     * 火车票规则基本信息.
     * </pre>
     *
     * <code>.api.TrainRuleItem.SettingItem settings = 1;</code>
     */
    public boolean hasSettings() {
      return settingsBuilder_ != null || settings_ != null;
    }
    /**
     * <pre>
     * 火车票规则基本信息.
     * </pre>
     *
     * <code>.api.TrainRuleItem.SettingItem settings = 1;</code>
     */
    public com.xingyun.policy.api.model.TrainRuleItem.SettingItem getSettings() {
      if (settingsBuilder_ == null) {
        return settings_ == null ? com.xingyun.policy.api.model.TrainRuleItem.SettingItem.getDefaultInstance() : settings_;
      } else {
        return settingsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 火车票规则基本信息.
     * </pre>
     *
     * <code>.api.TrainRuleItem.SettingItem settings = 1;</code>
     */
    public Builder setSettings(com.xingyun.policy.api.model.TrainRuleItem.SettingItem value) {
      if (settingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        settings_ = value;
        onChanged();
      } else {
        settingsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 火车票规则基本信息.
     * </pre>
     *
     * <code>.api.TrainRuleItem.SettingItem settings = 1;</code>
     */
    public Builder setSettings(
        com.xingyun.policy.api.model.TrainRuleItem.SettingItem.Builder builderForValue) {
      if (settingsBuilder_ == null) {
        settings_ = builderForValue.build();
        onChanged();
      } else {
        settingsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 火车票规则基本信息.
     * </pre>
     *
     * <code>.api.TrainRuleItem.SettingItem settings = 1;</code>
     */
    public Builder mergeSettings(com.xingyun.policy.api.model.TrainRuleItem.SettingItem value) {
      if (settingsBuilder_ == null) {
        if (settings_ != null) {
          settings_ =
            com.xingyun.policy.api.model.TrainRuleItem.SettingItem.newBuilder(settings_).mergeFrom(value).buildPartial();
        } else {
          settings_ = value;
        }
        onChanged();
      } else {
        settingsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 火车票规则基本信息.
     * </pre>
     *
     * <code>.api.TrainRuleItem.SettingItem settings = 1;</code>
     */
    public Builder clearSettings() {
      if (settingsBuilder_ == null) {
        settings_ = null;
        onChanged();
      } else {
        settings_ = null;
        settingsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 火车票规则基本信息.
     * </pre>
     *
     * <code>.api.TrainRuleItem.SettingItem settings = 1;</code>
     */
    public com.xingyun.policy.api.model.TrainRuleItem.SettingItem.Builder getSettingsBuilder() {
      
      onChanged();
      return getSettingsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 火车票规则基本信息.
     * </pre>
     *
     * <code>.api.TrainRuleItem.SettingItem settings = 1;</code>
     */
    public com.xingyun.policy.api.model.TrainRuleItem.SettingItemOrBuilder getSettingsOrBuilder() {
      if (settingsBuilder_ != null) {
        return settingsBuilder_.getMessageOrBuilder();
      } else {
        return settings_ == null ?
            com.xingyun.policy.api.model.TrainRuleItem.SettingItem.getDefaultInstance() : settings_;
      }
    }
    /**
     * <pre>
     * 火车票规则基本信息.
     * </pre>
     *
     * <code>.api.TrainRuleItem.SettingItem settings = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xingyun.policy.api.model.TrainRuleItem.SettingItem, com.xingyun.policy.api.model.TrainRuleItem.SettingItem.Builder, com.xingyun.policy.api.model.TrainRuleItem.SettingItemOrBuilder> 
        getSettingsFieldBuilder() {
      if (settingsBuilder_ == null) {
        settingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xingyun.policy.api.model.TrainRuleItem.SettingItem, com.xingyun.policy.api.model.TrainRuleItem.SettingItem.Builder, com.xingyun.policy.api.model.TrainRuleItem.SettingItemOrBuilder>(
                getSettings(),
                getParentForChildren(),
                isClean());
        settings_ = null;
      }
      return settingsBuilder_;
    }

    private java.util.List<com.xingyun.policy.api.model.TimeItem> times_ =
      java.util.Collections.emptyList();
    private void ensureTimesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        times_ = new java.util.ArrayList<com.xingyun.policy.api.model.TimeItem>(times_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xingyun.policy.api.model.TimeItem, com.xingyun.policy.api.model.TimeItem.Builder, com.xingyun.policy.api.model.TimeItemOrBuilder> timesBuilder_;

    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public java.util.List<com.xingyun.policy.api.model.TimeItem> getTimesList() {
      if (timesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(times_);
      } else {
        return timesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public int getTimesCount() {
      if (timesBuilder_ == null) {
        return times_.size();
      } else {
        return timesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public com.xingyun.policy.api.model.TimeItem getTimes(int index) {
      if (timesBuilder_ == null) {
        return times_.get(index);
      } else {
        return timesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public Builder setTimes(
        int index, com.xingyun.policy.api.model.TimeItem value) {
      if (timesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimesIsMutable();
        times_.set(index, value);
        onChanged();
      } else {
        timesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public Builder setTimes(
        int index, com.xingyun.policy.api.model.TimeItem.Builder builderForValue) {
      if (timesBuilder_ == null) {
        ensureTimesIsMutable();
        times_.set(index, builderForValue.build());
        onChanged();
      } else {
        timesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public Builder addTimes(com.xingyun.policy.api.model.TimeItem value) {
      if (timesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimesIsMutable();
        times_.add(value);
        onChanged();
      } else {
        timesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public Builder addTimes(
        int index, com.xingyun.policy.api.model.TimeItem value) {
      if (timesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimesIsMutable();
        times_.add(index, value);
        onChanged();
      } else {
        timesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public Builder addTimes(
        com.xingyun.policy.api.model.TimeItem.Builder builderForValue) {
      if (timesBuilder_ == null) {
        ensureTimesIsMutable();
        times_.add(builderForValue.build());
        onChanged();
      } else {
        timesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public Builder addTimes(
        int index, com.xingyun.policy.api.model.TimeItem.Builder builderForValue) {
      if (timesBuilder_ == null) {
        ensureTimesIsMutable();
        times_.add(index, builderForValue.build());
        onChanged();
      } else {
        timesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public Builder addAllTimes(
        java.lang.Iterable<? extends com.xingyun.policy.api.model.TimeItem> values) {
      if (timesBuilder_ == null) {
        ensureTimesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, times_);
        onChanged();
      } else {
        timesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public Builder clearTimes() {
      if (timesBuilder_ == null) {
        times_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        timesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public Builder removeTimes(int index) {
      if (timesBuilder_ == null) {
        ensureTimesIsMutable();
        times_.remove(index);
        onChanged();
      } else {
        timesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public com.xingyun.policy.api.model.TimeItem.Builder getTimesBuilder(
        int index) {
      return getTimesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public com.xingyun.policy.api.model.TimeItemOrBuilder getTimesOrBuilder(
        int index) {
      if (timesBuilder_ == null) {
        return times_.get(index);  } else {
        return timesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public java.util.List<? extends com.xingyun.policy.api.model.TimeItemOrBuilder> 
         getTimesOrBuilderList() {
      if (timesBuilder_ != null) {
        return timesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(times_);
      }
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public com.xingyun.policy.api.model.TimeItem.Builder addTimesBuilder() {
      return getTimesFieldBuilder().addBuilder(
          com.xingyun.policy.api.model.TimeItem.getDefaultInstance());
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public com.xingyun.policy.api.model.TimeItem.Builder addTimesBuilder(
        int index) {
      return getTimesFieldBuilder().addBuilder(
          index, com.xingyun.policy.api.model.TimeItem.getDefaultInstance());
    }
    /**
     * <pre>
     * 时间限制信息.
     * </pre>
     *
     * <code>repeated .api.TimeItem times = 2;</code>
     */
    public java.util.List<com.xingyun.policy.api.model.TimeItem.Builder> 
         getTimesBuilderList() {
      return getTimesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xingyun.policy.api.model.TimeItem, com.xingyun.policy.api.model.TimeItem.Builder, com.xingyun.policy.api.model.TimeItemOrBuilder> 
        getTimesFieldBuilder() {
      if (timesBuilder_ == null) {
        timesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.xingyun.policy.api.model.TimeItem, com.xingyun.policy.api.model.TimeItem.Builder, com.xingyun.policy.api.model.TimeItemOrBuilder>(
                times_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        times_ = null;
      }
      return timesBuilder_;
    }

    private int canUse_ ;
    /**
     * <pre>
     * 是否可用 (0:不可用 1:可用有政策 2:可用无政策).
     * </pre>
     *
     * <code>int32 can_use = 10;</code>
     */
    public int getCanUse() {
      return canUse_;
    }
    /**
     * <pre>
     * 是否可用 (0:不可用 1:可用有政策 2:可用无政策).
     * </pre>
     *
     * <code>int32 can_use = 10;</code>
     */
    public Builder setCanUse(int value) {
      
      canUse_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否可用 (0:不可用 1:可用有政策 2:可用无政策).
     * </pre>
     *
     * <code>int32 can_use = 10;</code>
     */
    public Builder clearCanUse() {
      
      canUse_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.TrainRuleDetailItem)
  }

  // @@protoc_insertion_point(class_scope:api.TrainRuleDetailItem)
  private static final com.xingyun.policy.api.model.TrainRuleDetailItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xingyun.policy.api.model.TrainRuleDetailItem();
  }

  public static com.xingyun.policy.api.model.TrainRuleDetailItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrainRuleDetailItem>
      PARSER = new com.google.protobuf.AbstractParser<TrainRuleDetailItem>() {
    public TrainRuleDetailItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TrainRuleDetailItem(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TrainRuleDetailItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrainRuleDetailItem> getParserForType() {
    return PARSER;
  }

  public com.xingyun.policy.api.model.TrainRuleDetailItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

