// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package com.xingyun.policy.api.dto.response;

/**
 * <pre>
 * 可扩充响应消息头，封装通用的请求消息头，可扩充.
 * </pre>
 *
 * Protobuf type {@code api.ResponseHeader}
 */
public  final class ResponseHeader extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.ResponseHeader)
    ResponseHeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResponseHeader.newBuilder() to construct.
  private ResponseHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResponseHeader() {
    traceId_ = "";
    totalTime_ = 0L;
    status_ = 0;
    msg_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResponseHeader(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            traceId_ = s;
            break;
          }
          case 16: {

            totalTime_ = input.readInt64();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            msg_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xingyun.policy.api.dto.response.Response.internal_static_api_ResponseHeader_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xingyun.policy.api.dto.response.Response.internal_static_api_ResponseHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xingyun.policy.api.dto.response.ResponseHeader.class, com.xingyun.policy.api.dto.response.ResponseHeader.Builder.class);
  }

  public static final int TRACE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object traceId_;
  /**
   * <pre>
   * 请求唯一的trace_id，全局唯一，响应头中带回，用于跟踪服务.
   * </pre>
   *
   * <code>string trace_id = 1;</code>
   */
  public java.lang.String getTraceId() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 请求唯一的trace_id，全局唯一，响应头中带回，用于跟踪服务.
   * </pre>
   *
   * <code>string trace_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTraceIdBytes() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_TIME_FIELD_NUMBER = 2;
  private long totalTime_;
  /**
   * <pre>
   * 服务总响应时间,ms.
   * </pre>
   *
   * <code>int64 total_time = 2;</code>
   */
  public long getTotalTime() {
    return totalTime_;
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private int status_;
  /**
   * <pre>
   * 通用状态，如参数校验等功能.
   * </pre>
   *
   * <code>.api.Status status = 3;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <pre>
   * 通用状态，如参数校验等功能.
   * </pre>
   *
   * <code>.api.Status status = 3;</code>
   */
  public com.xingyun.policy.api.enums.Status getStatus() {
    com.xingyun.policy.api.enums.Status result = com.xingyun.policy.api.enums.Status.valueOf(status_);
    return result == null ? com.xingyun.policy.api.enums.Status.UNRECOGNIZED : result;
  }

  public static final int MSG_FIELD_NUMBER = 11;
  private volatile java.lang.Object msg_;
  /**
   * <pre>
   * 错误消息，STATUS_SUCCESS时无此消息.
   * </pre>
   *
   * <code>string msg = 11;</code>
   */
  public java.lang.String getMsg() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 错误消息，STATUS_SUCCESS时无此消息.
   * </pre>
   *
   * <code>string msg = 11;</code>
   */
  public com.google.protobuf.ByteString
      getMsgBytes() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTraceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, traceId_);
    }
    if (totalTime_ != 0L) {
      output.writeInt64(2, totalTime_);
    }
    if (status_ != com.xingyun.policy.api.enums.Status.STATUS_EMPTY.getNumber()) {
      output.writeEnum(3, status_);
    }
    if (!getMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, msg_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTraceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, traceId_);
    }
    if (totalTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, totalTime_);
    }
    if (status_ != com.xingyun.policy.api.enums.Status.STATUS_EMPTY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, status_);
    }
    if (!getMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, msg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xingyun.policy.api.dto.response.ResponseHeader)) {
      return super.equals(obj);
    }
    com.xingyun.policy.api.dto.response.ResponseHeader other = (com.xingyun.policy.api.dto.response.ResponseHeader) obj;

    boolean result = true;
    result = result && getTraceId()
        .equals(other.getTraceId());
    result = result && (getTotalTime()
        == other.getTotalTime());
    result = result && status_ == other.status_;
    result = result && getMsg()
        .equals(other.getMsg());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRACE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceId().hashCode();
    hash = (37 * hash) + TOTAL_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalTime());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + MSG_FIELD_NUMBER;
    hash = (53 * hash) + getMsg().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xingyun.policy.api.dto.response.ResponseHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.dto.response.ResponseHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.dto.response.ResponseHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.dto.response.ResponseHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.dto.response.ResponseHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.dto.response.ResponseHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.dto.response.ResponseHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.dto.response.ResponseHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xingyun.policy.api.dto.response.ResponseHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.dto.response.ResponseHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xingyun.policy.api.dto.response.ResponseHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.dto.response.ResponseHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xingyun.policy.api.dto.response.ResponseHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 可扩充响应消息头，封装通用的请求消息头，可扩充.
   * </pre>
   *
   * Protobuf type {@code api.ResponseHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.ResponseHeader)
      com.xingyun.policy.api.dto.response.ResponseHeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xingyun.policy.api.dto.response.Response.internal_static_api_ResponseHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xingyun.policy.api.dto.response.Response.internal_static_api_ResponseHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xingyun.policy.api.dto.response.ResponseHeader.class, com.xingyun.policy.api.dto.response.ResponseHeader.Builder.class);
    }

    // Construct using com.xingyun.policy.api.dto.response.ResponseHeader.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      traceId_ = "";

      totalTime_ = 0L;

      status_ = 0;

      msg_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xingyun.policy.api.dto.response.Response.internal_static_api_ResponseHeader_descriptor;
    }

    public com.xingyun.policy.api.dto.response.ResponseHeader getDefaultInstanceForType() {
      return com.xingyun.policy.api.dto.response.ResponseHeader.getDefaultInstance();
    }

    public com.xingyun.policy.api.dto.response.ResponseHeader build() {
      com.xingyun.policy.api.dto.response.ResponseHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.xingyun.policy.api.dto.response.ResponseHeader buildPartial() {
      com.xingyun.policy.api.dto.response.ResponseHeader result = new com.xingyun.policy.api.dto.response.ResponseHeader(this);
      result.traceId_ = traceId_;
      result.totalTime_ = totalTime_;
      result.status_ = status_;
      result.msg_ = msg_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xingyun.policy.api.dto.response.ResponseHeader) {
        return mergeFrom((com.xingyun.policy.api.dto.response.ResponseHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xingyun.policy.api.dto.response.ResponseHeader other) {
      if (other == com.xingyun.policy.api.dto.response.ResponseHeader.getDefaultInstance()) return this;
      if (!other.getTraceId().isEmpty()) {
        traceId_ = other.traceId_;
        onChanged();
      }
      if (other.getTotalTime() != 0L) {
        setTotalTime(other.getTotalTime());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getMsg().isEmpty()) {
        msg_ = other.msg_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xingyun.policy.api.dto.response.ResponseHeader parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xingyun.policy.api.dto.response.ResponseHeader) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object traceId_ = "";
    /**
     * <pre>
     * 请求唯一的trace_id，全局唯一，响应头中带回，用于跟踪服务.
     * </pre>
     *
     * <code>string trace_id = 1;</code>
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 请求唯一的trace_id，全局唯一，响应头中带回，用于跟踪服务.
     * </pre>
     *
     * <code>string trace_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 请求唯一的trace_id，全局唯一，响应头中带回，用于跟踪服务.
     * </pre>
     *
     * <code>string trace_id = 1;</code>
     */
    public Builder setTraceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      traceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求唯一的trace_id，全局唯一，响应头中带回，用于跟踪服务.
     * </pre>
     *
     * <code>string trace_id = 1;</code>
     */
    public Builder clearTraceId() {
      
      traceId_ = getDefaultInstance().getTraceId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求唯一的trace_id，全局唯一，响应头中带回，用于跟踪服务.
     * </pre>
     *
     * <code>string trace_id = 1;</code>
     */
    public Builder setTraceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      traceId_ = value;
      onChanged();
      return this;
    }

    private long totalTime_ ;
    /**
     * <pre>
     * 服务总响应时间,ms.
     * </pre>
     *
     * <code>int64 total_time = 2;</code>
     */
    public long getTotalTime() {
      return totalTime_;
    }
    /**
     * <pre>
     * 服务总响应时间,ms.
     * </pre>
     *
     * <code>int64 total_time = 2;</code>
     */
    public Builder setTotalTime(long value) {
      
      totalTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 服务总响应时间,ms.
     * </pre>
     *
     * <code>int64 total_time = 2;</code>
     */
    public Builder clearTotalTime() {
      
      totalTime_ = 0L;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <pre>
     * 通用状态，如参数校验等功能.
     * </pre>
     *
     * <code>.api.Status status = 3;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * 通用状态，如参数校验等功能.
     * </pre>
     *
     * <code>.api.Status status = 3;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通用状态，如参数校验等功能.
     * </pre>
     *
     * <code>.api.Status status = 3;</code>
     */
    public com.xingyun.policy.api.enums.Status getStatus() {
      com.xingyun.policy.api.enums.Status result = com.xingyun.policy.api.enums.Status.valueOf(status_);
      return result == null ? com.xingyun.policy.api.enums.Status.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 通用状态，如参数校验等功能.
     * </pre>
     *
     * <code>.api.Status status = 3;</code>
     */
    public Builder setStatus(com.xingyun.policy.api.enums.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通用状态，如参数校验等功能.
     * </pre>
     *
     * <code>.api.Status status = 3;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object msg_ = "";
    /**
     * <pre>
     * 错误消息，STATUS_SUCCESS时无此消息.
     * </pre>
     *
     * <code>string msg = 11;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 错误消息，STATUS_SUCCESS时无此消息.
     * </pre>
     *
     * <code>string msg = 11;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 错误消息，STATUS_SUCCESS时无此消息.
     * </pre>
     *
     * <code>string msg = 11;</code>
     */
    public Builder setMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msg_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误消息，STATUS_SUCCESS时无此消息.
     * </pre>
     *
     * <code>string msg = 11;</code>
     */
    public Builder clearMsg() {
      
      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误消息，STATUS_SUCCESS时无此消息.
     * </pre>
     *
     * <code>string msg = 11;</code>
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msg_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.ResponseHeader)
  }

  // @@protoc_insertion_point(class_scope:api.ResponseHeader)
  private static final com.xingyun.policy.api.dto.response.ResponseHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xingyun.policy.api.dto.response.ResponseHeader();
  }

  public static com.xingyun.policy.api.dto.response.ResponseHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseHeader>
      PARSER = new com.google.protobuf.AbstractParser<ResponseHeader>() {
    public ResponseHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResponseHeader(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseHeader> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseHeader> getParserForType() {
    return PARSER;
  }

  public com.xingyun.policy.api.dto.response.ResponseHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

