// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.xingyun.policy.api.dto.request;

/**
 * <pre>
 * 政策检查请求.
 * </pre>
 *
 * Protobuf type {@code api.CheckRequest}
 */
public  final class CheckRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.CheckRequest)
    CheckRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckRequest.newBuilder() to construct.
  private CheckRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckRequest() {
    busiType_ = 0;
    items_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CheckRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.xingyun.policy.api.dto.request.RequestHeader.Builder subBuilder = null;
            if (header_ != null) {
              subBuilder = header_.toBuilder();
            }
            header_ = input.readMessage(com.xingyun.policy.api.dto.request.RequestHeader.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(header_);
              header_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            busiType_ = rawValue;
            break;
          }
          case 802: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              items_ = new java.util.ArrayList<com.google.protobuf.Any>();
              mutable_bitField0_ |= 0x00000004;
            }
            items_.add(
                input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xingyun.policy.api.dto.request.Request.internal_static_api_CheckRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xingyun.policy.api.dto.request.Request.internal_static_api_CheckRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xingyun.policy.api.dto.request.CheckRequest.class, com.xingyun.policy.api.dto.request.CheckRequest.Builder.class);
  }

  private int bitField0_;
  public static final int HEADER_FIELD_NUMBER = 1;
  private com.xingyun.policy.api.dto.request.RequestHeader header_;
  /**
   * <pre>
   * 请求头.
   * </pre>
   *
   * <code>.api.RequestHeader header = 1;</code>
   */
  public boolean hasHeader() {
    return header_ != null;
  }
  /**
   * <pre>
   * 请求头.
   * </pre>
   *
   * <code>.api.RequestHeader header = 1;</code>
   */
  public com.xingyun.policy.api.dto.request.RequestHeader getHeader() {
    return header_ == null ? com.xingyun.policy.api.dto.request.RequestHeader.getDefaultInstance() : header_;
  }
  /**
   * <pre>
   * 请求头.
   * </pre>
   *
   * <code>.api.RequestHeader header = 1;</code>
   */
  public com.xingyun.policy.api.dto.request.RequestHeaderOrBuilder getHeaderOrBuilder() {
    return getHeader();
  }

  public static final int BUSI_TYPE_FIELD_NUMBER = 2;
  private int busiType_;
  /**
   * <pre>
   * 政策业务类型.
   * </pre>
   *
   * <code>.api.BusiType busi_type = 2;</code>
   */
  public int getBusiTypeValue() {
    return busiType_;
  }
  /**
   * <pre>
   * 政策业务类型.
   * </pre>
   *
   * <code>.api.BusiType busi_type = 2;</code>
   */
  public com.xingyun.policy.api.enums.BusiType getBusiType() {
    com.xingyun.policy.api.enums.BusiType result = com.xingyun.policy.api.enums.BusiType.valueOf(busiType_);
    return result == null ? com.xingyun.policy.api.enums.BusiType.UNRECOGNIZED : result;
  }

  public static final int ITEMS_FIELD_NUMBER = 100;
  private java.util.List<com.google.protobuf.Any> items_;
  /**
   * <pre>
   * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any items = 100;</code>
   */
  public java.util.List<com.google.protobuf.Any> getItemsList() {
    return items_;
  }
  /**
   * <pre>
   * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any items = 100;</code>
   */
  public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <pre>
   * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any items = 100;</code>
   */
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <pre>
   * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any items = 100;</code>
   */
  public com.google.protobuf.Any getItems(int index) {
    return items_.get(index);
  }
  /**
   * <pre>
   * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any items = 100;</code>
   */
  public com.google.protobuf.AnyOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    if (busiType_ != com.xingyun.policy.api.enums.BusiType.BUSI_TYPE_EMPTY.getNumber()) {
      output.writeEnum(2, busiType_);
    }
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(100, items_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    if (busiType_ != com.xingyun.policy.api.enums.BusiType.BUSI_TYPE_EMPTY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, busiType_);
    }
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(100, items_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xingyun.policy.api.dto.request.CheckRequest)) {
      return super.equals(obj);
    }
    com.xingyun.policy.api.dto.request.CheckRequest other = (com.xingyun.policy.api.dto.request.CheckRequest) obj;

    boolean result = true;
    result = result && (hasHeader() == other.hasHeader());
    if (hasHeader()) {
      result = result && getHeader()
          .equals(other.getHeader());
    }
    result = result && busiType_ == other.busiType_;
    result = result && getItemsList()
        .equals(other.getItemsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    hash = (37 * hash) + BUSI_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + busiType_;
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xingyun.policy.api.dto.request.CheckRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.dto.request.CheckRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.dto.request.CheckRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.dto.request.CheckRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.dto.request.CheckRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xingyun.policy.api.dto.request.CheckRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xingyun.policy.api.dto.request.CheckRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.dto.request.CheckRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xingyun.policy.api.dto.request.CheckRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.dto.request.CheckRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xingyun.policy.api.dto.request.CheckRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xingyun.policy.api.dto.request.CheckRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xingyun.policy.api.dto.request.CheckRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 政策检查请求.
   * </pre>
   *
   * Protobuf type {@code api.CheckRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.CheckRequest)
      com.xingyun.policy.api.dto.request.CheckRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xingyun.policy.api.dto.request.Request.internal_static_api_CheckRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xingyun.policy.api.dto.request.Request.internal_static_api_CheckRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xingyun.policy.api.dto.request.CheckRequest.class, com.xingyun.policy.api.dto.request.CheckRequest.Builder.class);
    }

    // Construct using com.xingyun.policy.api.dto.request.CheckRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (headerBuilder_ == null) {
        header_ = null;
      } else {
        header_ = null;
        headerBuilder_ = null;
      }
      busiType_ = 0;

      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xingyun.policy.api.dto.request.Request.internal_static_api_CheckRequest_descriptor;
    }

    public com.xingyun.policy.api.dto.request.CheckRequest getDefaultInstanceForType() {
      return com.xingyun.policy.api.dto.request.CheckRequest.getDefaultInstance();
    }

    public com.xingyun.policy.api.dto.request.CheckRequest build() {
      com.xingyun.policy.api.dto.request.CheckRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.xingyun.policy.api.dto.request.CheckRequest buildPartial() {
      com.xingyun.policy.api.dto.request.CheckRequest result = new com.xingyun.policy.api.dto.request.CheckRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (headerBuilder_ == null) {
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      result.busiType_ = busiType_;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xingyun.policy.api.dto.request.CheckRequest) {
        return mergeFrom((com.xingyun.policy.api.dto.request.CheckRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xingyun.policy.api.dto.request.CheckRequest other) {
      if (other == com.xingyun.policy.api.dto.request.CheckRequest.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (other.busiType_ != 0) {
        setBusiTypeValue(other.getBusiTypeValue());
      }
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000004);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xingyun.policy.api.dto.request.CheckRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xingyun.policy.api.dto.request.CheckRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.xingyun.policy.api.dto.request.RequestHeader header_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xingyun.policy.api.dto.request.RequestHeader, com.xingyun.policy.api.dto.request.RequestHeader.Builder, com.xingyun.policy.api.dto.request.RequestHeaderOrBuilder> headerBuilder_;
    /**
     * <pre>
     * 请求头.
     * </pre>
     *
     * <code>.api.RequestHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return headerBuilder_ != null || header_ != null;
    }
    /**
     * <pre>
     * 请求头.
     * </pre>
     *
     * <code>.api.RequestHeader header = 1;</code>
     */
    public com.xingyun.policy.api.dto.request.RequestHeader getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? com.xingyun.policy.api.dto.request.RequestHeader.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 请求头.
     * </pre>
     *
     * <code>.api.RequestHeader header = 1;</code>
     */
    public Builder setHeader(com.xingyun.policy.api.dto.request.RequestHeader value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
        onChanged();
      } else {
        headerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 请求头.
     * </pre>
     *
     * <code>.api.RequestHeader header = 1;</code>
     */
    public Builder setHeader(
        com.xingyun.policy.api.dto.request.RequestHeader.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
        onChanged();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 请求头.
     * </pre>
     *
     * <code>.api.RequestHeader header = 1;</code>
     */
    public Builder mergeHeader(com.xingyun.policy.api.dto.request.RequestHeader value) {
      if (headerBuilder_ == null) {
        if (header_ != null) {
          header_ =
            com.xingyun.policy.api.dto.request.RequestHeader.newBuilder(header_).mergeFrom(value).buildPartial();
        } else {
          header_ = value;
        }
        onChanged();
      } else {
        headerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 请求头.
     * </pre>
     *
     * <code>.api.RequestHeader header = 1;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = null;
        onChanged();
      } else {
        header_ = null;
        headerBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 请求头.
     * </pre>
     *
     * <code>.api.RequestHeader header = 1;</code>
     */
    public com.xingyun.policy.api.dto.request.RequestHeader.Builder getHeaderBuilder() {
      
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 请求头.
     * </pre>
     *
     * <code>.api.RequestHeader header = 1;</code>
     */
    public com.xingyun.policy.api.dto.request.RequestHeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            com.xingyun.policy.api.dto.request.RequestHeader.getDefaultInstance() : header_;
      }
    }
    /**
     * <pre>
     * 请求头.
     * </pre>
     *
     * <code>.api.RequestHeader header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xingyun.policy.api.dto.request.RequestHeader, com.xingyun.policy.api.dto.request.RequestHeader.Builder, com.xingyun.policy.api.dto.request.RequestHeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xingyun.policy.api.dto.request.RequestHeader, com.xingyun.policy.api.dto.request.RequestHeader.Builder, com.xingyun.policy.api.dto.request.RequestHeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private int busiType_ = 0;
    /**
     * <pre>
     * 政策业务类型.
     * </pre>
     *
     * <code>.api.BusiType busi_type = 2;</code>
     */
    public int getBusiTypeValue() {
      return busiType_;
    }
    /**
     * <pre>
     * 政策业务类型.
     * </pre>
     *
     * <code>.api.BusiType busi_type = 2;</code>
     */
    public Builder setBusiTypeValue(int value) {
      busiType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 政策业务类型.
     * </pre>
     *
     * <code>.api.BusiType busi_type = 2;</code>
     */
    public com.xingyun.policy.api.enums.BusiType getBusiType() {
      com.xingyun.policy.api.enums.BusiType result = com.xingyun.policy.api.enums.BusiType.valueOf(busiType_);
      return result == null ? com.xingyun.policy.api.enums.BusiType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 政策业务类型.
     * </pre>
     *
     * <code>.api.BusiType busi_type = 2;</code>
     */
    public Builder setBusiType(com.xingyun.policy.api.enums.BusiType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      busiType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 政策业务类型.
     * </pre>
     *
     * <code>.api.BusiType busi_type = 2;</code>
     */
    public Builder clearBusiType() {
      
      busiType_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.Any> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        items_ = new java.util.ArrayList<com.google.protobuf.Any>(items_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> itemsBuilder_;

    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public java.util.List<com.google.protobuf.Any> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public com.google.protobuf.Any getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public Builder setItems(
        int index, com.google.protobuf.Any value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public Builder setItems(
        int index, com.google.protobuf.Any.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public Builder addItems(com.google.protobuf.Any value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public Builder addItems(
        int index, com.google.protobuf.Any value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public Builder addItems(
        com.google.protobuf.Any.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public Builder addItems(
        int index, com.google.protobuf.Any.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.google.protobuf.Any> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public com.google.protobuf.Any.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public com.google.protobuf.AnyOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public com.google.protobuf.Any.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          com.google.protobuf.Any.getDefaultInstance());
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public com.google.protobuf.Any.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, com.google.protobuf.Any.getDefaultInstance());
    }
    /**
     * <pre>
     * 业务相关数据请求,如FlightCheckItem，CarCheckItem.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any items = 100;</code>
     */
    public java.util.List<com.google.protobuf.Any.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                items_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.CheckRequest)
  }

  // @@protoc_insertion_point(class_scope:api.CheckRequest)
  private static final com.xingyun.policy.api.dto.request.CheckRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xingyun.policy.api.dto.request.CheckRequest();
  }

  public static com.xingyun.policy.api.dto.request.CheckRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckRequest>
      PARSER = new com.google.protobuf.AbstractParser<CheckRequest>() {
    public CheckRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CheckRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CheckRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckRequest> getParserForType() {
    return PARSER;
  }

  public com.xingyun.policy.api.dto.request.CheckRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

