// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.xingyun.policy.api.dto.request;

public interface ListDetailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.ListDetailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 请求头.
   * </pre>
   *
   * <code>.api.RequestHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <pre>
   * 请求头.
   * </pre>
   *
   * <code>.api.RequestHeader header = 1;</code>
   */
  com.xingyun.policy.api.dto.request.RequestHeader getHeader();
  /**
   * <pre>
   * 请求头.
   * </pre>
   *
   * <code>.api.RequestHeader header = 1;</code>
   */
  com.xingyun.policy.api.dto.request.RequestHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * 用户id列表.
   * </pre>
   *
   * <code>repeated int64 cuids = 2;</code>
   */
  java.util.List<java.lang.Long> getCuidsList();
  /**
   * <pre>
   * 用户id列表.
   * </pre>
   *
   * <code>repeated int64 cuids = 2;</code>
   */
  int getCuidsCount();
  /**
   * <pre>
   * 用户id列表.
   * </pre>
   *
   * <code>repeated int64 cuids = 2;</code>
   */
  long getCuids(int index);

  /**
   * <pre>
   * 业务类型.
   * </pre>
   *
   * <code>.api.BusiType busi_type = 3;</code>
   */
  int getBusiTypeValue();
  /**
   * <pre>
   * 业务类型.
   * </pre>
   *
   * <code>.api.BusiType busi_type = 3;</code>
   */
  com.xingyun.policy.api.enums.BusiType getBusiType();
}
