// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.xingyun.policy.api.dto.request;

public interface PageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.PageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 页码，[1,n].
   * </pre>
   *
   * <code>int32 page_num = 1;</code>
   */
  int getPageNum();

  /**
   * <pre>
   * 分页大小.如果获取的是全部数据, 该字段值为0.
   * </pre>
   *
   * <code>int32 page_size = 2;</code>
   */
  int getPageSize();
}
