// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.xingyun.policy.api.dto.request;

public final class Request {
  private Request() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_RequestHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_RequestHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_PageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_PageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_CheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_CheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_ListDetailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_ListDetailRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\022\003api\032\031google/protobuf/an" +
      "y.proto\032\013enums.proto\"a\n\rRequestHeader\022\020\n" +
      "\010trace_id\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022\016\n\006source\030\003" +
      " \001(\t\022!\n\003ext\030d \001(\0132\024.google.protobuf.Any\"" +
      "2\n\013PageRequest\022\020\n\010page_num\030\001 \001(\005\022\021\n\tpage" +
      "_size\030\002 \001(\005\"y\n\014CheckRequest\022\"\n\006header\030\001 " +
      "\001(\0132\022.api.RequestHeader\022 \n\tbusi_type\030\002 \001" +
      "(\0162\r.api.BusiType\022#\n\005items\030d \003(\0132\024.googl" +
      "e.protobuf.Any\"`\n\013ListRequest\022\"\n\006header\030" +
      "\001 \001(\0132\022.api.RequestHeader\022\013\n\003eid\030\002 \001(\003\022 " +
      "\n\tbusi_type\030\003 \001(\0162\r.api.BusiType\"h\n\021List" +
      "DetailRequest\022\"\n\006header\030\001 \001(\0132\022.api.Requ" +
      "estHeader\022\r\n\005cuids\030\002 \003(\003\022 \n\tbusi_type\030\003 " +
      "\001(\0162\r.api.BusiTypeB&\n\"com.xingyun.policy" +
      ".api.dto.requestP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.xingyun.policy.api.enums.Enums.getDescriptor(),
        }, assigner);
    internal_static_api_RequestHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_RequestHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_RequestHeader_descriptor,
        new java.lang.String[] { "TraceId", "Key", "Source", "Ext", });
    internal_static_api_PageRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_PageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_PageRequest_descriptor,
        new java.lang.String[] { "PageNum", "PageSize", });
    internal_static_api_CheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_CheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_CheckRequest_descriptor,
        new java.lang.String[] { "Header", "BusiType", "Items", });
    internal_static_api_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_api_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_ListRequest_descriptor,
        new java.lang.String[] { "Header", "Eid", "BusiType", });
    internal_static_api_ListDetailRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_api_ListDetailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_ListDetailRequest_descriptor,
        new java.lang.String[] { "Header", "Cuids", "BusiType", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.xingyun.policy.api.enums.Enums.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
