// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

package com.xingyun.policy.api.enums;

/**
 * <pre>
 * 政策基本业务类型.
 * </pre>
 *
 * Protobuf enum {@code api.BusiType}
 */
public enum BusiType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 空值.
   * </pre>
   *
   * <code>BUSI_TYPE_EMPTY = 0;</code>
   */
  BUSI_TYPE_EMPTY(0),
  /**
   * <pre>
   * 用车.
   * </pre>
   *
   * <code>BUSI_TYPE_CAR = 1;</code>
   */
  BUSI_TYPE_CAR(1),
  /**
   * <pre>
   * 机票.
   * </pre>
   *
   * <code>BUSI_TYPE_FLIGHT = 2;</code>
   */
  BUSI_TYPE_FLIGHT(2),
  /**
   * <pre>
   * 火车票.
   * </pre>
   *
   * <code>BUSI_TYPE_TRAIN = 3;</code>
   */
  BUSI_TYPE_TRAIN(3),
  /**
   * <pre>
   * 酒店.
   * </pre>
   *
   * <code>BUSI_TYPE_HOTEL = 4;</code>
   */
  BUSI_TYPE_HOTEL(4),
  /**
   * <pre>
   * 汽车票.
   * </pre>
   *
   * <code>BUSI_TYPE_BUSTICKET = 7;</code>
   */
  BUSI_TYPE_BUSTICKET(7),
  /**
   * <pre>
   * 支付.
   * </pre>
   *
   * <code>BUSI_TYPE_PAY = 8;</code>
   */
  BUSI_TYPE_PAY(8),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 空值.
   * </pre>
   *
   * <code>BUSI_TYPE_EMPTY = 0;</code>
   */
  public static final int BUSI_TYPE_EMPTY_VALUE = 0;
  /**
   * <pre>
   * 用车.
   * </pre>
   *
   * <code>BUSI_TYPE_CAR = 1;</code>
   */
  public static final int BUSI_TYPE_CAR_VALUE = 1;
  /**
   * <pre>
   * 机票.
   * </pre>
   *
   * <code>BUSI_TYPE_FLIGHT = 2;</code>
   */
  public static final int BUSI_TYPE_FLIGHT_VALUE = 2;
  /**
   * <pre>
   * 火车票.
   * </pre>
   *
   * <code>BUSI_TYPE_TRAIN = 3;</code>
   */
  public static final int BUSI_TYPE_TRAIN_VALUE = 3;
  /**
   * <pre>
   * 酒店.
   * </pre>
   *
   * <code>BUSI_TYPE_HOTEL = 4;</code>
   */
  public static final int BUSI_TYPE_HOTEL_VALUE = 4;
  /**
   * <pre>
   * 汽车票.
   * </pre>
   *
   * <code>BUSI_TYPE_BUSTICKET = 7;</code>
   */
  public static final int BUSI_TYPE_BUSTICKET_VALUE = 7;
  /**
   * <pre>
   * 支付.
   * </pre>
   *
   * <code>BUSI_TYPE_PAY = 8;</code>
   */
  public static final int BUSI_TYPE_PAY_VALUE = 8;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static BusiType valueOf(int value) {
    return forNumber(value);
  }

  public static BusiType forNumber(int value) {
    switch (value) {
      case 0: return BUSI_TYPE_EMPTY;
      case 1: return BUSI_TYPE_CAR;
      case 2: return BUSI_TYPE_FLIGHT;
      case 3: return BUSI_TYPE_TRAIN;
      case 4: return BUSI_TYPE_HOTEL;
      case 7: return BUSI_TYPE_BUSTICKET;
      case 8: return BUSI_TYPE_PAY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<BusiType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      BusiType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<BusiType>() {
          public BusiType findValueByNumber(int number) {
            return BusiType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.xingyun.policy.api.enums.Enums.getDescriptor().getEnumTypes().get(1);
  }

  private static final BusiType[] VALUES = values();

  public static BusiType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private BusiType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:api.BusiType)
}

