// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

package com.xingyun.policy.api.enums;

/**
 * <pre>
 * 位置类型.
 * </pre>
 *
 * Protobuf enum {@code api.LocationSrcType}
 */
public enum LocationSrcType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 空值.
   * </pre>
   *
   * <code>LOCATION_SRC_TYPE_EMPTY = 0;</code>
   */
  LOCATION_SRC_TYPE_EMPTY(0),
  /**
   * <pre>
   * 出发地.
   * </pre>
   *
   * <code>LOCATION_SRC_TYPE_DEPART = 1;</code>
   */
  LOCATION_SRC_TYPE_DEPART(1),
  /**
   * <pre>
   * 目的地.
   * </pre>
   *
   * <code>LOCATION_SRC_TYPE_DEST = 2;</code>
   */
  LOCATION_SRC_TYPE_DEST(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 空值.
   * </pre>
   *
   * <code>LOCATION_SRC_TYPE_EMPTY = 0;</code>
   */
  public static final int LOCATION_SRC_TYPE_EMPTY_VALUE = 0;
  /**
   * <pre>
   * 出发地.
   * </pre>
   *
   * <code>LOCATION_SRC_TYPE_DEPART = 1;</code>
   */
  public static final int LOCATION_SRC_TYPE_DEPART_VALUE = 1;
  /**
   * <pre>
   * 目的地.
   * </pre>
   *
   * <code>LOCATION_SRC_TYPE_DEST = 2;</code>
   */
  public static final int LOCATION_SRC_TYPE_DEST_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LocationSrcType valueOf(int value) {
    return forNumber(value);
  }

  public static LocationSrcType forNumber(int value) {
    switch (value) {
      case 0: return LOCATION_SRC_TYPE_EMPTY;
      case 1: return LOCATION_SRC_TYPE_DEPART;
      case 2: return LOCATION_SRC_TYPE_DEST;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LocationSrcType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LocationSrcType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LocationSrcType>() {
          public LocationSrcType findValueByNumber(int number) {
            return LocationSrcType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.xingyun.policy.api.enums.Enums.getDescriptor().getEnumTypes().get(4);
  }

  private static final LocationSrcType[] VALUES = values();

  public static LocationSrcType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LocationSrcType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:api.LocationSrcType)
}

